=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/xsd/AccessLevels.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="access" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:byte" name="level" use="required"/>
								<xs:attribute type="xs:string" name="name" use="required"/>
								<xs:attribute type="xs:string" name="nameColor" use="required"/>
								<xs:attribute type="xs:string" name="useNameColor" use="required"/>
								<xs:attribute type="xs:string" name="titleColor" use="required"/>
								<xs:attribute type="xs:string" name="useTitleColor" use="required"/>
								<xs:attribute type="xs:string" name="isGm" use="required"/>
								<xs:attribute type="xs:string" name="allowPeaceAttack" use="required"/>
								<xs:attribute type="xs:string" name="allowFixedRes" use="required"/>
								<xs:attribute type="xs:string" name="allowTransaction" use="required"/>
								<xs:attribute type="xs:string" name="allowAltg" use="required"/>
								<xs:attribute type="xs:string" name="giveDamage" use="required"/>
								<xs:attribute type="xs:string" name="takeAggro" use="required"/>
								<xs:attribute type="xs:string" name="gainExp" use="required"/>
								<xs:attribute type="xs:string" name="canDisableGmStatus" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/config/AccessLevels.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../data/xsd/AccessLevels.xsd">
	<!-- Access levels -->
	<access level="100" name="Master Access" nameColor="00CCFF" useNameColor="true" titleColor="00CCFF" useTitleColor="false" isGm="true" allowPeaceAttack="true" allowFixedRes="true" allowTransaction="true" allowAltg="true" giveDamage="true" takeAggro="true" gainExp="true" canDisableGmStatus="true" />
	<access level="90" name="Head GM" nameColor="00FFFF" useNameColor="true" titleColor="00FFFF" useTitleColor="false" isGm="true" allowPeaceAttack="true" allowFixedRes="true" allowTransaction="true" allowAltg="true" giveDamage="true" takeAggro="true" gainExp="true" canDisableGmStatus="true" />
	<access level="80" name="Event GM" nameColor="00FFFF" useNameColor="true" titleColor="00FFFF" useTitleColor="false" isGm="true" allowPeaceAttack="true" allowFixedRes="true" allowTransaction="false" allowAltg="true" giveDamage="false" takeAggro="false" gainExp="false" canDisableGmStatus="false" />
	<access level="70" name="Support GM" nameColor="00FFFF" useNameColor="true" titleColor="00FFFF" useTitleColor="false" isGm="true" allowPeaceAttack="false" allowFixedRes="true" allowTransaction="false" allowAltg="true" giveDamage="false" takeAggro="false" gainExp="false" canDisableGmStatus="false" />
	<access level="60" name="General GM" nameColor="00FFFF" useNameColor="true" titleColor="00FFFF" useTitleColor="false" isGm="true" allowPeaceAttack="false" allowFixedRes="true" allowTransaction="false" allowAltg="true" giveDamage="false" takeAggro="false" gainExp="false" canDisableGmStatus="false" />
	<access level="50" name="Test GM" nameColor="FFFFFF" useNameColor="true" titleColor="FFFFFF" useTitleColor="false" isGm="false" allowPeaceAttack="false" allowFixedRes="true" allowTransaction="false" allowAltg="true" giveDamage="false" takeAggro="false" gainExp="false" canDisableGmStatus="false" />
	<access level="0" name="User" nameColor="FFFFFF" useNameColor="false" titleColor="ECF9A2" useTitleColor="false" isGm="false" allowPeaceAttack="false" allowFixedRes="false" allowTransaction="true" allowAltg="false" giveDamage="true" takeAggro="true" gainExp="true" canDisableGmStatus="false" />
</list>
