=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/xsd/Boats.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="path" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="point" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:short" name="speed1" use="required"/>
											<xs:attribute type="xs:short" name="speed2" use="required"/>
											<xs:attribute type="xs:int" name="x" use="required"/>
											<xs:attribute type="xs:int" name="y" use="required"/>
											<xs:attribute type="xs:short" name="z" use="required"/>
											<xs:attribute type="xs:int" name="time" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:byte" name="id" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="boat" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="name" use="required"/>
								<xs:attribute type="xs:byte" name="id" use="required"/>
								<xs:attribute type="xs:int" name="spawnX" use="required"/>
								<xs:attribute type="xs:int" name="spawnY" use="required"/>
								<xs:attribute type="xs:short" name="spawnZ" use="required"/>
								<xs:attribute type="xs:int" name="heading" use="required"/>
								<xs:attribute type="xs:byte" name="pathIdA" use="required"/>
								<xs:attribute type="xs:short" name="ticketA" use="required"/>
								<xs:attribute type="xs:int" name="xTeleNoTicketA" use="required"/>
								<xs:attribute type="xs:int" name="yTeleNoTicketA" use="required"/>
								<xs:attribute type="xs:short" name="zTeleNoTicketA" use="required"/>
								<xs:attribute type="xs:string" name="announcerA" use="required"/>
								<xs:attribute type="xs:string" name="message10A" use="required"/>
								<xs:attribute type="xs:string" name="message5A" use="required"/>
								<xs:attribute type="xs:string" name="message1A" use="required"/>
								<xs:attribute type="xs:string" name="message0A" use="required"/>
								<xs:attribute type="xs:string" name="messageBeginA" use="required"/>
								<xs:attribute type="xs:byte" name="pathIdB" use="required"/>
								<xs:attribute type="xs:short" name="ticketB" use="required"/>
								<xs:attribute type="xs:int" name="xTeleNoTicketB" use="required"/>
								<xs:attribute type="xs:int" name="yTeleNoTicketB" use="required"/>
								<xs:attribute type="xs:short" name="zTeleNoTicketB" use="required"/>
								<xs:attribute type="xs:string" name="announcerB" use="required"/>
								<xs:attribute type="xs:string" name="message10B" use="required"/>
								<xs:attribute type="xs:string" name="message5B" use="required"/>
								<xs:attribute type="xs:string" name="message1B" use="required"/>
								<xs:attribute type="xs:string" name="message0B" use="required"/>
								<xs:attribute type="xs:string" name="messageBeginB" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/Boats.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Boats.xsd">
	<path id="1"> <!-- Talking Island to Gludin -->
		<point speed1="180" speed2="800" x="-121385" y="261660" z="-3610" time="-12" />
		<point speed1="200" speed2="800" x="-127694" y="253312" z="-3610" time="55500" />
		<point speed1="250" speed2="800" x="-129274" y="237060" z="-3610" time="65300" />
		<point speed1="200" speed2="800" x="-114688" y="139040" z="-3610" time="495900" />
		<point speed1="180" speed2="800" x="-109663" y="135704" z="-3610" time="-8" />
		<point speed1="180" speed2="800" x="-102151" y="135704" z="-3610" time="-7" />
		<point speed1="180" speed2="800" x="-96686" y="140595" z="-3610" time="-6" />
		<point speed1="180" speed2="800" x="-95686" y="147718" z="-3610" time="-5" />
		<point speed1="180" speed2="800" x="-95686" y="148718" z="-3610" time="-4" />
		<point speed1="150" speed2="800" x="-95686" y="149718" z="-3610" time="-3" />
		<point speed1="150" speed2="800" x="-95686" y="150514" z="-3610" time="-2" />
	</path>
	<path id="2"> <!-- Gludin to Talking Island -->
		<point speed1="180" speed2="800" x="-95686" y="155514" z="-3610" time="-12" />
		<point speed1="250" speed2="800" x="-95686" y="185514" z="-3610" time="111800" />
		<point speed1="200" speed2="800" x="-60136" y="238816" z="-3610" time="330200" />
		<point speed1="180" speed2="1800" x="-60520" y="259609" z="-3610" time="115800" />
		<point speed1="180" speed2="1800" x="-65344" y="261460" z="-3610" time="-8" />
		<point speed1="180" speed2="1800" x="-83344" y="261560" z="-3610" time="-7" />
		<point speed1="180" speed2="1800" x="-88344" y="261660" z="-3610" time="-6" />
		<point speed1="150" speed2="1800" x="-92344" y="261660" z="-3610" time="-5" />
		<point speed1="150" speed2="1800" x="-95622" y="261660" z="-3610" time="-4" />
		<point speed1="150" speed2="1800" x="-96622" y="261660" z="-3610" time="-3" />
	</path>
	<path id="3"> <!-- Giran to Talking Island -->
		<point speed1="150" speed2="800" x="51914" y="189023" z="-3610" time="-18" />
		<point speed1="200" speed2="800" x="60567" y="189789" z="-3610" time="44200" />
		<point speed1="250" speed2="800" x="63732" y="197457" z="-3610" time="33600" />
		<point speed1="250" speed2="800" x="63732" y="207457" z="-3610" time="40500" />
		<point speed1="250" speed2="800" x="60434" y="219306" z="-3610" time="49900" />
		<point speed1="300" speed2="800" x="56115" y="225303" z="-3610" time="24700" />
		<point speed1="300" speed2="800" x="41634" y="226047" z="-3610" time="51900" />
		<point speed1="300" speed2="800" x="27153" y="226791" z="-3610" time="50100" />
		<point speed1="300" speed2="800" x="12672" y="227535" z="-3610" time="49400" />
		<point speed1="300" speed2="800" x="-1808" y="228280" z="-3610" time="49800" />
		<point speed1="300" speed2="800" x="-22165" y="231742" z="-3610" time="69400" />
		<point speed1="250" speed2="800" x="-42523" y="235205" z="-3610" time="83200" />
		<point speed1="200" speed2="800" x="-68451" y="259960" z="-3610" time="178700" />
		<point speed1="180" speed2="800" x="-83344" y="261610" z="-3610" time="-5" />
		<point speed1="180" speed2="800" x="-88344" y="261660" z="-3610" time="-4" />
		<point speed1="150" speed2="800" x="-92344" y="261660" z="-3610" time="-3" />
		<point speed1="150" speed2="1800" x="-96622" y="261660" z="-3610" time="-1" />
	</path>
	<path id="4"> <!-- Talking Island to Giran -->
		<point speed1="180" speed2="800" x="-113925" y="261660" z="-3610" time="-18" />
		<point speed1="180" speed2="800" x="-126107" y="249116" z="-3610" time="-17" />
		<point speed1="180" speed2="800" x="-126107" y="234499" z="-3610" time="-16" />
		<point speed1="180" speed2="800" x="-126107" y="219882" z="-3610" time="-15" />
		<point speed1="180" speed2="800" x="-109414" y="204914" z="-3610" time="-14" />
		<point speed1="250" speed2="800" x="-92807" y="204914" z="-3610" time="68400" />
		<point speed1="250" speed2="800" x="-80425" y="216450" z="-3610" time="69300" />
		<point speed1="250" speed2="800" x="-68043" y="227987" z="-3610" time="67900" />
		<point speed1="200" speed2="800" x="-60844" y="231369" z="-3610" time="39200" />
		<point speed1="200" speed2="800" x="-44915" y="231369" z="-3610" time="80800" />
		<point speed1="200" speed2="800" x="-28986" y="231369" z="-3610" time="81900" />
		<point speed1="180" speed2="800" x="8233" y="207624" z="-3610" time="-7" />
		<point speed1="180" speed2="800" x="21470" y="201503" z="-3610" time="-6" />
		<point speed1="150" speed2="800" x="40058" y="195383" z="-3610" time="-5" />
		<point speed1="150" speed2="800" x="43022" y="193793" z="-3610" time="-4" />
		<point speed1="150" speed2="800" x="45986" y="192203" z="-3610" time="-3" />
		<point speed1="150" speed2="1800" x="48950" y="190613" z="-3610" time="-1" />
	</path>
	<path id="5"> <!-- Gludin to Rune -->
		<point speed1="150" speed2="800" x="-95686" y="155514" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="-97727" y="160575" z="-3610" time="-1" />
		<point speed1="180" speed2="800" x="-108048" y="158380" z="-3610" time="-1" />
		<point speed1="300" speed2="800" x="-107964" y="91102" z="-3610" time="-1" />
		<point speed1="300" speed2="800" x="-66492" y="47880" z="-3610" time="-1" />
		<point speed1="250" speed2="800" x="-56257" y="40932" z="-3610" time="-1" />
		<point speed1="300" speed2="800" x="-33367" y="16345" z="-3610" time="-1" />
		<point speed1="250" speed2="800" x="-27195" y="1065" z="-3610" time="-1" />
		<point speed1="250" speed2="800" x="34000" y="1065" z="-3610" time="-1" />
		<point speed1="180" speed2="800" x="44914" y="-25021" z="-3610" time="-1" />
		<point speed1="180" speed2="800" x="43496" y="-27864" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="39077" y="-32922" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="36650" y="-35468" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="34400" y="-37670" z="-3610" time="-1" />	
	</path>
	<path id="6"> <!-- Rune to Gludin -->
		<point speed1="150" speed2="800" x="31622" y="-40501" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="2493" y="-29776" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="-13722" y="3629" z="-3610" time="421823" />
		<point speed1="180" speed2="800" x="-28875" y="15029" z="-3610" time="105347" />
		<point speed1="200" speed2="800" x="-33367" y="16345" z="-3610" time="23404" />
		<point speed1="250" speed2="800" x="-56257" y="40932" z="-3610" time="134371" />
		<point speed1="250" speed2="800" x="-66492" y="47880" z="-3610" time="49482" />
		<point speed1="300" speed2="800" x="-107964" y="91102" z="-3610" time="199668" />
		<point speed1="300" speed2="800" x="-107531" y="126510" z="-3610" time="118035" />
		<point speed1="300" speed2="1800" x="-96686" y="140595" z="-3610" time="59255" />
		<point speed1="250" speed2="1800" x="-95686" y="147718" z="-3610" time="28771" />
		<point speed1="150" speed2="1800" x="-95686" y="148718" z="-3610" time="-1" />
		<point speed1="150" speed2="1800" x="-95686" y="149718" z="-3610" time="-1" />
		<point speed1="150" speed2="1800" x="-95686" y="150500" z="-3610" time="-1" />
	</path>
	<path id="7"> <!-- Innandril tour -->
		<point speed1="150" speed2="800" x="105129" y="226240" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="90604" y="238797" z="-3610" time="128002" />
		<point speed1="150" speed2="800" x="74853" y="237943" z="-3610" time="105161" />
		<point speed1="150" speed2="800" x="68207" y="235399" z="-3610" time="47442" />
		<point speed1="150" speed2="800" x="63226" y="230487" z="-3610" time="46637" />
		<point speed1="150" speed2="800" x="61843" y="224797" z="-3610" time="39038" />
		<point speed1="150" speed2="800" x="61822" y="203066" z="-3610" time="144873" />
		<point speed1="150" speed2="800" x="59051" y="197685" z="-3610" time="40350" />
		<point speed1="150" speed2="800" x="54048" y="195298" z="-3610" time="36955" />
		<point speed1="150" speed2="800" x="41609" y="195687" z="-3610" time="82967" />
		<point speed1="150" speed2="800" x="35821" y="200284" z="-3610" time="49276" />
		<point speed1="150" speed2="800" x="35567" y="205265" z="-3610" time="33250" />
		<point speed1="150" speed2="800" x="35617" y="222471" z="-3610" time="114707" />
		<point speed1="150" speed2="800" x="37932" y="226588" z="-3610" time="31488" />
		<point speed1="150" speed2="800" x="42932" y="229394" z="-3610" time="38224" />
		<point speed1="150" speed2="800" x="74324" y="245231" z="-3610" time="234404" />
		<point speed1="150" speed2="800" x="81872" y="250314" z="-3610" time="60666" />
		<point speed1="150" speed2="800" x="101692" y="249882" z="-3610" time="132165" />
		<point speed1="150" speed2="800" x="107907" y="256073" z="-3610" time="58483" />
		<point speed1="150" speed2="800" x="112317" y="257133" z="-3610" time="30237" />
		<point speed1="150" speed2="800" x="126273" y="255313" z="-3610" time="93828" />
		<point speed1="150" speed2="800" x="128067" y="250961" z="-3610" time="31382" />
		<point speed1="150" speed2="800" x="128520" y="238249" z="-3610" time="84800" />
		<point speed1="150" speed2="800" x="126428" y="235072" z="-3610" time="25359" />
		<point speed1="150" speed2="800" x="121843" y="234656" z="-3610" time="30692" />
		<point speed1="150" speed2="800" x="120096" y="234268" z="-3610" time="11930" />
		<point speed1="150" speed2="800" x="118572" y="233046" z="-3610" time="13023" />
		<point speed1="150" speed2="800" x="117671" y="228951" z="-3610" time="27953" />
		<point speed1="150" speed2="800" x="115936" y="226540" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="113628" y="226240" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="111300" y="226240" z="-3610" time="-1" />
		<point speed1="150" speed2="800" x="111264" y="226240" z="-3610" time="-1" />	
	</path>
	<path id="8"> <!-- Rune to Primeval -->
