=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/xsd/Doors.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="door" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="name" use="required"/>
								<xs:attribute type="xs:int" name="id" use="required"/>
								<xs:attribute type="xs:int" name="x" use="required"/>
								<xs:attribute type="xs:int" name="y" use="required"/>
								<xs:attribute type="xs:short" name="z" use="required"/>
								<xs:attribute type="xs:int" name="xMin" use="required"/>
								<xs:attribute type="xs:int" name="yMin" use="required"/>
								<xs:attribute type="xs:short" name="zMin" use="required"/>
								<xs:attribute type="xs:int" name="xMax" use="required"/>
								<xs:attribute type="xs:int" name="yMax" use="required"/>
								<xs:attribute type="xs:short" name="zMax" use="required"/>
								<xs:attribute type="xs:int" name="hp" use="required"/>
								<xs:attribute type="xs:int" name="pDef" use="required"/>
								<xs:attribute type="xs:short" name="mDef" use="required"/>
								<xs:attribute type="xs:string" name="unlockable" use="required"/>
								<xs:attribute type="xs:string" name="isOpen" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/Doors.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/Doors.xsd">
	<!-- Doors on region 16_20 -->
	<!-- Normil's Garden -->
	<door name="Normils_garden_01" id="16200001" x="-109704" y="76424" z="-12656" xMin="-109819" yMin="76415" zMin="-12656" xMax="-109589" yMax="76435" zMax="-12612" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_02" id="16200002" x="-110856" y="77960" z="-12848" xMin="-110874" yMin="77861" zMin="-12848" xMax="-110838" yMax="78060" zMax="-12804" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_03" id="16200003" x="-111624" y="77960" z="-12848" xMin="-111642" yMin="77861" zMin="-12848" xMax="-111606" yMax="78060" zMax="-12804" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_04" id="16200004" x="-107587" y="80604" z="-12946" xMin="-107607" yMin="80506" zMin="-12946" xMax="-107573" yMax="80702" zMax="-12886" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_05" id="16200005" x="-109120" y="80648" z="-12944" xMin="-109141" yMin="80451" zMin="-12944" xMax="-109100" yMax="80844" zMax="-12876" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_06" id="16200006" x="-108676" y="82444" z="-12912" xMin="-108830" yMin="82290" zMin="-12912" xMax="-108521" yMax="82599" zMax="-12844" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_07" id="16200007" x="-110475" y="83143" z="-12912" xMin="-110658" yMin="83137" zMin="-12912" xMax="-110287" yMax="83150" zMax="-12828" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_08" id="16200008" x="-112264" y="82440" z="-12912" xMin="-112416" yMin="82286" zMin="-12912" xMax="-112109" yMax="82594" zMax="-12844" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_09" id="16200009" x="-111824" y="80648" z="-12944" xMin="-111845" yMin="80451" zMin="-12944" xMax="-111804" yMax="80844" zMax="-12876" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_10" id="16200010" x="-107588" y="83677" z="-12913" xMin="-107608" yMin="83580" zMin="-12913" xMax="-107575" yMax="83776" zMax="-12855" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_11" id="16200011" x="-110472" y="84488" z="-13008" xMin="-110587" yMin="84479" zMin="-13008" xMax="-110357" yMax="84499" zMax="-12964" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_12" id="16200012" x="-111424" y="87176" z="-13008" xMin="-111445" yMin="86979" zMin="-13008" xMax="-111404" yMax="87372" zMax="-12938" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_13" id="16200013" x="-110663" y="84052" z="-13011" xMin="-110683" yMin="83955" zMin="-13011" xMax="-110649" yMax="84151" zMax="-13003" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_14" id="16200014" x="-113183" y="87179" z="-12904" xMin="-113194" yMin="87037" zMin="-12904" xMax="-113173" yMax="87323" zMax="-12852" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_15" id="16200015" x="-115074" y="87178" z="-12816" xMin="-115085" yMin="87035" zMin="-12816" xMax="-115063" yMax="87322" zMax="-12744" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_16" id="16200016" x="-116972" y="87177" z="-12711" xMin="-116983" yMin="87034" zMin="-12711" xMax="-116961" yMax="87320" zMax="-12711" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_17" id="16200017" x="-108898" y="82223" z="-12878" xMin="-108898" yMin="82223" zMin="-12878" xMax="-108898" yMax="82223" zMax="-12878" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_18" id="16200018" x="-110476" y="82844" z="-12878" xMin="-110476" yMin="82844" zMin="-12878" xMax="-110476" yMax="82844" zMax="-12878" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_19" id="16200019" x="-112043" y="82231" z="-12878" xMin="-112043" yMin="82231" zMin="-12878" xMax="-112043" yMax="82231" zMax="-12878" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_20" id="16200022" x="-107475" y="83666" z="-12884" xMin="-107475" yMin="87177" zMin="-12884" xMax="-107475" yMax="87177" zMax="-12884" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_21" id="16200023" x="-109201" y="81920" z="-12907" xMin="-109328" yMin="81792" zMin="-12907" xMax="-108801" yMax="82320" zMax="-12847" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_22" id="16200024" x="-110473" y="82417" z="-12906" xMin="-110603" yMin="82366" zMin="-12906" xMax="-110342" yMax="82854" zMax="-12850" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="Normils_garden_23" id="16200025" x="-111741" y="81914" z="-12908" xMin="-112141" yMin="81786" zMin="-12908" xMax="-111611" yMax="82316" zMax="-12846" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<!-- Doors on region 17_10 -->
	<!-- Olympiad Arena -->
	<door name="olympiadarena_Door_001" id="17100001" x="-88824" y="-252637" z="-3342" xMin="-88836" yMin="-252766" zMin="-3342" xMax="-88810" yMax="-252510" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100002" x="-87184" y="-252637" z="-3342" xMin="-87200" yMin="-252766" zMin="-3342" xMax="-87165" yMax="-252510" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100003" x="-84599" y="-252637" z="-3342" xMin="-84611" yMin="-252766" zMin="-3342" xMax="-84585" yMax="-252510" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100004" x="-82959" y="-252637" z="-3342" xMin="-82975" yMin="-252766" zMin="-3342" xMax="-82940" yMax="-252510" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100005" x="-80410" y="-252637" z="-3342" xMin="-80422" yMin="-252766" zMin="-3342" xMax="-80396" yMax="-252510" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100006" x="-78749" y="-252637" z="-3342" xMin="-78765" yMin="-252766" zMin="-3342" xMax="-78730" yMax="-252510" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100007" x="-76491" y="-252637" z="-3342" xMin="-76503" yMin="-252766" zMin="-3342" xMax="-76477" yMax="-252510" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100008" x="-74851" y="-252637" z="-3342" xMin="-74867" yMin="-252766" zMin="-3342" xMax="-74832" yMax="-252510" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100009" x="-88824" y="-249762" z="-3342" xMin="-88836" yMin="-249891" zMin="-3342" xMax="-88810" yMax="-249635" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100010" x="-87184" y="-249762" z="-3342" xMin="-87200" yMin="-249891" zMin="-3342" xMax="-87165" yMax="-249635" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100011" x="-84599" y="-249762" z="-3342" xMin="-84611" yMin="-249891" zMin="-3342" xMax="-84585" yMax="-249635" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100012" x="-82959" y="-249762" z="-3342" xMin="-82975" yMin="-249891" zMin="-3342" xMax="-82940" yMax="-249635" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100013" x="-80410" y="-249762" z="-3342" xMin="-80422" yMin="-249891" zMin="-3342" xMax="-80396" yMax="-249635" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100014" x="-78770" y="-249762" z="-3342" xMin="-78786" yMin="-249891" zMin="-3342" xMax="-78751" yMax="-249635" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100015" x="-76491" y="-249762" z="-3342" xMin="-76503" yMin="-249891" zMin="-3342" xMax="-76477" yMax="-249635" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100016" x="-74851" y="-249762" z="-3342" xMin="-74867" yMin="-249891" zMin="-3342" xMax="-74832" yMax="-249635" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100017" x="-88824" y="-246955" z="-3342" xMin="-88836" yMin="-247084" zMin="-3342" xMax="-88810" yMax="-246828" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
	<door name="olympiadarena_Door_001" id="17100018" x="-87184" y="-246955" z="-3342" xMin="-87200" yMin="-247084" zMin="-3342" xMax="-87165" yMax="-246828" zMax="-3242" hp="158250" pDef="644" mDef="518" unlockable="false" isOpen="false" />
