=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/xsd/experience.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="table">
		<complexType>
			<sequence minOccurs="1" maxOccurs="1">
				<element name="experience" minOccurs="1" maxOccurs="87">
					<complexType>
						<attribute name="level" use="required">
							<simpleType>
								<restriction base="positiveInteger">
									<minInclusive value="1" />
									<maxInclusive value="87" />
								</restriction>
							</simpleType>
						</attribute>
						<attribute name="tolevel" type="nonNegativeInteger" use="required" />
					</complexType>
				</element>
			</sequence>
			<attribute name="maxLevel" use="required">
				<simpleType>
					<restriction base="positiveInteger">
						<minInclusive value="1" />
						<maxInclusive value="87" />
					</restriction>
				</simpleType>
			</attribute>
			<attribute name="maxPetLevel" use="required">
				<simpleType>
					<restriction base="positiveInteger">
						<minInclusive value="1" />
						<maxInclusive value="87" />
					</restriction>
				</simpleType>
			</attribute>
		</complexType>
	</element>
</schema>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/stats/experience.xml
<?xml version="1.0" encoding="UTF-8"?>
<table maxLevel="80" maxPetLevel="80" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/experience.xsd">
	<experience level="1" tolevel="0" />
	<experience level="2" tolevel="68" />
	<experience level="3" tolevel="363" />
	<experience level="4" tolevel="1168" />
	<experience level="5" tolevel="2884" />
	<experience level="6" tolevel="6038" />
	<experience level="7" tolevel="11287" />
	<experience level="8" tolevel="19423" />
	<experience level="9" tolevel="31378" />
	<experience level="10" tolevel="48229" />
	<experience level="11" tolevel="71201" />
	<experience level="12" tolevel="101676" />
	<experience level="13" tolevel="141192" />
	<experience level="14" tolevel="191452" />
	<experience level="15" tolevel="254327" />
	<experience level="16" tolevel="331864" />
	<experience level="17" tolevel="426284" />
	<experience level="18" tolevel="539995" />
	<experience level="19" tolevel="675590" />
	<experience level="20" tolevel="835854" />
	<experience level="21" tolevel="1023775" />
	<experience level="22" tolevel="1242536" />
	<experience level="23" tolevel="1495531" />
	<experience level="24" tolevel="1786365" />
	<experience level="25" tolevel="2118860" />
	<experience level="26" tolevel="2497059" />
	<experience level="27" tolevel="2925229" />
	<experience level="28" tolevel="3407873" />
	<experience level="29" tolevel="3949727" />
	<experience level="30" tolevel="4555766" />
	<experience level="31" tolevel="5231213" />
	<experience level="32" tolevel="5981539" />
	<experience level="33" tolevel="6812472" />
	<experience level="34" tolevel="7729999" />
	<experience level="35" tolevel="8740372" />
	<experience level="36" tolevel="9850111" />
	<experience level="37" tolevel="11066012" />
	<experience level="38" tolevel="12395149" />
	<experience level="39" tolevel="13844879" />
	<experience level="40" tolevel="15422851" />
	<experience level="41" tolevel="17137002" />
	<experience level="42" tolevel="18995573" />
	<experience level="43" tolevel="21007103" />
	<experience level="44" tolevel="23180442" />
	<experience level="45" tolevel="25524751" />
	<experience level="46" tolevel="28049509" />
	<experience level="47" tolevel="30764519" />
	<experience level="48" tolevel="33679907" />
	<experience level="49" tolevel="36806133" />
	<experience level="50" tolevel="40153995" />
	<experience level="51" tolevel="45524865" />
	<experience level="52" tolevel="51262204" />
	<experience level="53" tolevel="57383682" />
	<experience level="54" tolevel="63907585" />
	<experience level="55" tolevel="70852742" />
	<experience level="56" tolevel="80700339" />
	<experience level="57" tolevel="91162131" />
	<experience level="58" tolevel="102265326" />
	<experience level="59" tolevel="114038008" />
	<experience level="60" tolevel="126509030" />
	<experience level="61" tolevel="146307211" />
	<experience level="62" tolevel="167243291" />
	<experience level="63" tolevel="189363788" />
	<experience level="64" tolevel="212716741" />
	<experience level="65" tolevel="237351413" />
	<experience level="66" tolevel="271973532" />
	<experience level="67" tolevel="308441375" />
	<experience level="68" tolevel="346825235" />
	<experience level="69" tolevel="387197529" />
	<experience level="70" tolevel="429632402" />
	<experience level="71" tolevel="474205751" />
	<experience level="72" tolevel="532692055" />
	<experience level="73" tolevel="606319094" />
	<experience level="74" tolevel="696376867" />
	<experience level="75" tolevel="804219972" />
	<experience level="76" tolevel="931275828" />
	<experience level="77" tolevel="1151275834" />
	<experience level="78" tolevel="1511275834" />
	<experience level="79" tolevel="2099275834" />
	<experience level="80" tolevel="4200000000" />
	<experience level="81" tolevel="6300000000" />
	<experience level="82" tolevel="8820000000" />
	<experience level="83" tolevel="11844000000" />
	<experience level="84" tolevel="15472800000" />
	<experience level="85" tolevel="19827360000" />
	<experience level="86" tolevel="25314105600" />
	<experience level="87" tolevel="32211728640" />
</table>
