=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/xsd/items.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="item">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="set">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="val" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="0" name="for">
								<xs:complexType>
									<xs:sequence>
										<xs:choice maxOccurs="unbounded">
											<xs:element maxOccurs="unbounded" name="set">
												<xs:complexType>
													<xs:sequence minOccurs="0">
														<xs:element name="and">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="game">
																		<xs:complexType>
																			<xs:attribute name="chance" type="xs:unsignedByte" use="required" />
																			<xs:attribute name="skill" type="xs:boolean" use="optional" />
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
													<xs:attribute name="val" type="xs:unsignedShort" use="required" />
													<xs:attribute name="order" type="xs:string" use="required" />
													<xs:attribute name="stat" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element name="add">
												<xs:complexType>
													<xs:sequence minOccurs="0">
														<xs:element name="and">
															<xs:complexType>
																<xs:sequence>
																	<xs:element minOccurs="0" name="player">
																		<xs:complexType>
																			<xs:attribute name="behind" type="xs:string" use="optional" />
																			<xs:attribute name="hp" type="xs:unsignedByte" use="optional" />
																		</xs:complexType>
																	</xs:element>
																	<xs:element minOccurs="0" name="using">
																		<xs:complexType>
																			<xs:attribute name="slotitem" type="xs:string" use="required" />
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
													<xs:attribute name="val" type="xs:short" use="required" />
													<xs:attribute name="order" type="xs:string" use="required" />
													<xs:attribute name="stat" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element name="enchant">
												<xs:complexType>
													<xs:attribute name="val" type="xs:unsignedByte" use="required" />
													<xs:attribute name="order" type="xs:string" use="required" />
													<xs:attribute name="stat" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element name="sub">
												<xs:complexType>
													<xs:sequence minOccurs="0">
														<xs:element name="and">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="game">
																		<xs:complexType>
																			<xs:attribute name="skill" type="xs:boolean" use="required" />
																			<xs:attribute name="chance" type="xs:unsignedByte" use="required" />
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
													<xs:attribute name="val" type="xs:unsignedByte" use="required" />
													<xs:attribute name="order" type="xs:string" use="required" />
													<xs:attribute name="stat" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element name="mul">
												<xs:complexType>
													<xs:sequence minOccurs="0">
														<xs:element name="and">
															<xs:complexType>
																<xs:sequence>
																	<xs:element minOccurs="0" name="player">
																		<xs:complexType>
																			<xs:attribute name="hp" type="xs:unsignedByte" use="required" />
																		</xs:complexType>
																	</xs:element>
																	<xs:element minOccurs="0" name="using">
																		<xs:complexType>
																			<xs:attribute name="slotitem" type="xs:string" use="required" />
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
													<xs:attribute name="val" type="xs:decimal" use="required" />
													<xs:attribute name="order" type="xs:string" use="required" />
													<xs:attribute name="stat" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element name="skill">
												<xs:complexType>
													<xs:attribute name="onCrit" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="id" type="xs:unsignedShort" use="required" />
													<xs:attribute name="lvl" type="xs:unsignedByte" use="required" />
													<xs:attribute name="chance" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="onCast" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedShort" use="required" />
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/stats/items/9200-9299.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="9200" type="Armor" name="Jester Hat - Firework">
		<!-- A festive, shadow-type jester hat with 2 points. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="bodypart" val="dhair"/>
		<set name="armor_type" val="none"/>
		<set name="weight" val="10"/>
		<set name="crystal_type" val="none"/>
		<set name="duration" val="300"/>
		<set name="sellable" val="false"/>
		<set name="dropable" val="false"/>
		<set name="tradeable" val="false"/>
		<for>
			<add val="0" order="0x10" stat="pDef"/>
		</for>
	</item>
	<item id="9201" type="Armor" name="Wizard Hat - Firework">
		<!-- A shadow-type wizard hat with a wide brim and bent tip. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="bodypart" val="dhair"/>
		<set name="armor_type" val="none"/>
		<set name="weight" val="10"/>
		<set name="crystal_type" val="none"/>
		<set name="duration" val="300"/>
		<set name="sellable" val="false"/>
		<set name="dropable" val="false"/>
		<set name="tradeable" val="false"/>
		<for>
			<add val="0" order="0x10" stat="pDef"/>
		</for>
	</item>
	<item id="9202" type="Armor" name="Dapper Hat - Firework">
		<!-- A shadow-type hair accessory with a visor. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="bodypart" val="dhair"/>
		<set name="armor_type" val="none"/>
		<set name="weight" val="10"/>
		<set name="crystal_type" val="none"/>
		<set name="duration" val="300"/>
		<set name="sellable" val="false"/>
		<set name="dropable" val="false"/>
		<set name="tradeable" val="false"/>
		<for>
			<add val="0" order="0x10" stat="pDef"/>
		</for>
	</item>
	<item id="9203" type="Armor" name="Romantic Chapeau - Firework">
		<!-- A shadow-type hair accessory adorned with feathers. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="bodypart" val="dhair"/>
		<set name="armor_type" val="none"/>
		<set name="weight" val="10"/>
		<set name="crystal_type" val="none"/>
		<set name="duration" val="300"/>
		<set name="sellable" val="false"/>
		<set name="dropable" val="false"/>
		<set name="tradeable" val="false"/>
		<for>
			<add val="0" order="0x10" stat="pDef"/>
		</for>
	</item>
	<item id="9204" type="Armor" name="Iron Circlet - Firework">
		<!-- A shadow-type hair accessory made of iron. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="bodypart" val="dhair"/>
		<set name="armor_type" val="none"/>
		<set name="weight" val="10"/>
		<set name="crystal_type" val="none"/>
		<set name="duration" val="300"/>
		<set name="sellable" val="false"/>
		<set name="dropable" val="false"/>
		<set name="tradeable" val="false"/>
		<for>
			<add val="0" order="0x10" stat="pDef"/>
		</for>
	</item>
	<item id="9205" type="EtcItem" name="Alchemist's Chest Key (Event)">
		<!-- A key to open an Alchemist's Treasure Chest. For use in events only -->
		<set name="item_type" val="none"/>
		<set name="weight" val="10"/>
		<set name="consume_type" val="stackable"/>
		<set name="crystal_type" val="none"/>
	</item>
	<item id="9206" type="EtcItem" name="Greater Healing Potion (Event)">
		<!-- A magical potion that quickly restores HP. Its effect lasts for 15 seconds. Designed for use in events only. -->
		<set name="item_type" val="potion"/>
		<set name="weight" val="5"/>
		<set name="consume_type" val="stackable"/>
		<set name="crystal_type" val="none"/>
	</item>
	<item id="9207" type="EtcItem" name="Quick Healing Potion (Event)">
		<!-- A magical potion that quickly restores HP. Its effect is temporary. Designed for use in events only. -->
		<set name="item_type" val="potion"/>
		<set name="weight" val="5"/>
		<set name="consume_type" val="stackable"/>
		<set name="crystal_type" val="none"/>
	</item>
	<item id="9208" type="Armor" name="Phantom Mask (Event)">
		<!-- A feathered hair accessory. This item cannot be exchanged or dropped. -->
		<set name="bodypart" val="dhair"/>
		<set name="armor_type" val="none"/>
		<set name="weight" val="10"/>
		<set name="crystal_type" val="none"/>
		<set name="sellable" val="false"/>
		<set name="dropable" val="false"/>
		<set name="tradeable" val="false"/>
		<for>
			<add val="0" order="0x10" stat="pDef"/>
		</for>
	</item>
</list>
