=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/xsd/ManorSeeds.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="seed" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:short" name="id" use="required"/>
								<xs:attribute type="xs:byte" name="level" use="required"/>
								<xs:attribute type="xs:short" name="cropId" use="required"/>
								<xs:attribute type="xs:short" name="matureId" use="required"/>
								<xs:attribute type="xs:short" name="reward1" use="required"/>
								<xs:attribute type="xs:short" name="reward2" use="required"/>
								<xs:attribute type="xs:byte" name="castleId" use="required"/>
								<xs:attribute type="xs:boolean" name="isAlternative" use="required"/>
								<xs:attribute type="xs:short" name="seedLimit" use="required"/>
								<xs:attribute type="xs:short" name="cropLimit" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/ManorSeeds.xml
<?xml version='1.0' encoding='utf-8'?>
<!-- This file contains all special info about seeds. -->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/ManorSeeds.xsd">
	<seed id="5016" level="10" cropId="5073" matureId="5103" reward1="1864" reward2="1878" castleId="1" isAlternative="false" seedLimit="8100" cropLimit="9000"/> <!-- Seed: Dark Coda -->
	<seed id="5017" level="13" cropId="5068" matureId="5098" reward1="1865" reward2="1879" castleId="1" isAlternative="false" seedLimit="8100" cropLimit="9000"/> <!-- Seed: Red Coda -->
	<seed id="5018" level="16" cropId="5065" matureId="5095" reward1="1866" reward2="1874" castleId="1" isAlternative="false" seedLimit="8100" cropLimit="9000"/> <!-- Seed: Chilly Coda -->
	<seed id="5019" level="19" cropId="5067" matureId="5097" reward1="1867" reward2="1894" castleId="1" isAlternative="false" seedLimit="4050" cropLimit="4500"/> <!-- Seed: Blue Coda -->
	<seed id="5020" level="22" cropId="5069" matureId="5099" reward1="1868" reward2="1876" castleId="1" isAlternative="false" seedLimit="2025" cropLimit="2250"/> <!-- Seed: Golden Coda -->
	<seed id="5021" level="25" cropId="5071" matureId="5101" reward1="1869" reward2="1895" castleId="1" isAlternative="false" seedLimit="1350" cropLimit="1500"/> <!-- Seed: Lute Coda -->
	<seed id="5022" level="28" cropId="5070" matureId="5100" reward1="1870" reward2="1877" castleId="1" isAlternative="false" seedLimit="2025" cropLimit="2250"/> <!-- Seed: Desert Coda -->
	<seed id="5023" level="37" cropId="5077" matureId="5107" reward1="1873" reward2="4044" castleId="1" isAlternative="false" seedLimit="810" cropLimit="900"/> <!-- Seed: Blue Cobol -->
	<seed id="5024" level="19" cropId="5067" matureId="5097" reward1="1867" reward2="1894" castleId="2" isAlternative="false" seedLimit="4194" cropLimit="4660"/> <!-- Seed: Blue Coda -->
	<seed id="5025" level="22" cropId="5069" matureId="5099" reward1="1868" reward2="1876" castleId="2" isAlternative="false" seedLimit="2097" cropLimit="2330"/> <!-- Seed: Golden Coda -->
	<seed id="5026" level="25" cropId="5071" matureId="5101" reward1="1869" reward2="1895" castleId="2" isAlternative="false" seedLimit="1398" cropLimit="1553"/> <!-- Seed: Lute Coda -->
	<seed id="5027" level="28" cropId="5070" matureId="5100" reward1="1870" reward2="1877" castleId="2" isAlternative="false" seedLimit="2097" cropLimit="2330"/> <!-- Seed: Desert Coda -->
	<seed id="5028" level="31" cropId="5078" matureId="5108" reward1="1871" reward2="4042" castleId="2" isAlternative="false" seedLimit="2097" cropLimit="2330"/> <!-- Seed: Red Cobol -->
	<seed id="5029" level="34" cropId="5075" matureId="5105" reward1="1872" reward2="1880" castleId="2" isAlternative="false" seedLimit="1677" cropLimit="1864"/> <!-- Seed: Chilly Cobol -->
	<seed id="5030" level="40" cropId="5082" matureId="5112" reward1="1864" reward2="5549" castleId="2" isAlternative="false" seedLimit="838" cropLimit="932"/> <!-- Seed: Thorn Cobol -->
	<seed id="5031" level="43" cropId="5079" matureId="5109" reward1="1865" reward2="4039" castleId="2" isAlternative="false" seedLimit="838" cropLimit="932"/> <!-- Seed: Golden Cobol -->
	<seed id="5032" level="46" cropId="5084" matureId="5114" reward1="1866" reward2="1885" castleId="2" isAlternative="false" seedLimit="838" cropLimit="932"/> <!-- Seed: Great Cobol -->
	<seed id="5033" level="31" cropId="5078" matureId="5108" reward1="1871" reward2="4042" castleId="3" isAlternative="false" seedLimit="2250" cropLimit="2500"/> <!-- Seed: Red Cobol -->
	<seed id="5034" level="34" cropId="5075" matureId="5105" reward1="1872" reward2="1880" castleId="3" isAlternative="false" seedLimit="1800" cropLimit="2000"/> <!-- Seed: Chilly Cobol -->
	<seed id="5035" level="37" cropId="5077" matureId="5107" reward1="1873" reward2="4044" castleId="3" isAlternative="false" seedLimit="900" cropLimit="1000"/> <!-- Seed: Blue Cobol -->
	<seed id="5036" level="40" cropId="5082" matureId="5112" reward1="1864" reward2="5549" castleId="3" isAlternative="false" seedLimit="900" cropLimit="1000"/> <!-- Seed: Thorn Cobol -->
	<seed id="5037" level="43" cropId="5079" matureId="5109" reward1="1865" reward2="4039" castleId="3" isAlternative="false" seedLimit="900" cropLimit="1000"/> <!-- Seed: Golden Cobol -->
	<seed id="5038" level="46" cropId="5084" matureId="5114" reward1="1866" reward2="1885" castleId="3" isAlternative="false" seedLimit="900" cropLimit="1000"/> <!-- Seed: Great Cobol -->
	<seed id="5039" level="49" cropId="5088" matureId="5118" reward1="1867" reward2="4043" castleId="3" isAlternative="false" seedLimit="1125" cropLimit="1250"/> <!-- Seed: Red Codran -->
	<seed id="5040" level="58" cropId="5092" matureId="5122" reward1="1871" reward2="4040" castleId="3" isAlternative="false" seedLimit="900" cropLimit="1000"/> <!-- Seed: Twin Codran -->
	<seed id="5041" level="64" cropId="5090" matureId="5120" reward1="1873" reward2="5550" castleId="3" isAlternative="false" seedLimit="450" cropLimit="500"/> <!-- Seed: Desert Codran -->
	<seed id="5042" level="10" cropId="5073" matureId="5103" reward1="1864" reward2="1878" castleId="4" isAlternative="false" seedLimit="7200" cropLimit="8000"/> <!-- Seed: Dark Coda -->
	<seed id="5043" level="13" cropId="5068" matureId="5098" reward1="1865" reward2="1879" castleId="4" isAlternative="false" seedLimit="7200" cropLimit="8000"/> <!-- Seed: Red Coda -->
	<seed id="5044" level="19" cropId="5067" matureId="5097" reward1="1867" reward2="1894" castleId="4" isAlternative="false" seedLimit="3600" cropLimit="4000"/> <!-- Seed: Blue Coda -->
	<seed id="5045" level="31" cropId="5078" matureId="5108" reward1="1871" reward2="4042" castleId="4" isAlternative="false" seedLimit="1800" cropLimit="2000"/> <!-- Seed: Red Cobol -->
	<seed id="5046" level="34" cropId="5075" matureId="5105" reward1="1872" reward2="1880" castleId="4" isAlternative="false" seedLimit="1440" cropLimit="1600"/> <!-- Seed: Chilly Cobol -->
	<seed id="5047" level="37" cropId="5077" matureId="5107" reward1="1873" reward2="4044" castleId="4" isAlternative="false" seedLimit="720" cropLimit="800"/> <!-- Seed: Blue Cobol -->
	<seed id="5048" level="40" cropId="5082" matureId="5112" reward1="1864" reward2="5549" castleId="4" isAlternative="false" seedLimit="720" cropLimit="800"/> <!-- Seed: Thorn Cobol -->
	<seed id="5049" level="50" cropId="5091" matureId="5121" reward1="1868" reward2="1884" castleId="4" isAlternative="false" seedLimit="720" cropLimit="800"/> <!-- Seed: Sea Codran -->
	<seed id="5050" level="52" cropId="5085" matureId="5115" reward1="1869" reward2="4041" castleId="4" isAlternative="false" seedLimit="900" cropLimit="1000"/> <!-- Seed: Chilly Codran -->
	<seed id="5051" level="55" cropId="5087" matureId="5117" reward1="1870" reward2="1882" castleId="4" isAlternative="false" seedLimit="720" cropLimit="800"/> <!-- Seed: Blue Codran -->
	<seed id="5052" level="58" cropId="5092" matureId="5122" reward1="1871" reward2="4040" castleId="4" isAlternative="false" seedLimit="720" cropLimit="800"/> <!-- Seed: Twin Codran -->
	<seed id="5053" level="40" cropId="5082" matureId="5112" reward1="1864" reward2="5549" castleId="5" isAlternative="false" seedLimit="1344" cropLimit="1494"/> <!-- Seed: Thorn Cobol -->
	<seed id="5054" level="43" cropId="5079" matureId="5109" reward1="1865" reward2="4039" castleId="5" isAlternative="false" seedLimit="1344" cropLimit="1494"/> <!-- Seed: Golden Cobol -->
	<seed id="5055" level="46" cropId="5084" matureId="5114" reward1="1866" reward2="1885" castleId="5" isAlternative="false" seedLimit="1344" cropLimit="1494"/> <!-- Seed: Great Cobol -->
	<seed id="5056" level="49" cropId="5088" matureId="5118" reward1="1867" reward2="4043" castleId="5" isAlternative="false" seedLimit="1680" cropLimit="1867"/> <!-- Seed: Red Codran -->
	<seed id="5057" level="52" cropId="5085" matureId="5115" reward1="1869" reward2="4041" castleId="5" isAlternative="false" seedLimit="1680" cropLimit="1867"/> <!-- Seed: Chilly Codran -->
	<seed id="5058" level="55" cropId="5087" matureId="5117" reward1="1870" reward2="1882" castleId="5" isAlternative="false" seedLimit="1344" cropLimit="1494"/> <!-- Seed: Blue Codran -->
	<seed id="5059" level="58" cropId="5092" matureId="5122" reward1="1871" reward2="4040" castleId="5" isAlternative="false" seedLimit="1344" cropLimit="1494"/> <!-- Seed: Twin Codran -->
	<seed id="5060" level="61" cropId="5094" matureId="5124" reward1="1872" reward2="1881" castleId="5" isAlternative="false" seedLimit="896" cropLimit="996"/> <!-- Seed: Great Codran -->
	<seed id="5061" level="64" cropId="5090" matureId="5120" reward1="1873" reward2="5550" castleId="5" isAlternative="false" seedLimit="672" cropLimit="747"/> <!-- Seed: Desert Codran -->
	<seed id="5221" level="34" cropId="5075" matureId="5105" reward1="1872" reward2="1880" castleId="6" isAlternative="false" seedLimit="2592" cropLimit="2880"/> <!-- Seed: Chilly Cobol -->
	<seed id="5222" level="37" cropId="5077" matureId="5107" reward1="1873" reward2="4044" castleId="6" isAlternative="false" seedLimit="1296" cropLimit="1440"/> <!-- Seed: Blue Cobol -->
	<seed id="5223" level="40" cropId="5082" matureId="5112" reward1="1864" reward2="5549" castleId="6" isAlternative="false" seedLimit="1296" cropLimit="1440"/> <!-- Seed: Thorn Cobol -->
	<seed id="5224" level="43" cropId="5079" matureId="5109" reward1="1865" reward2="4039" castleId="6" isAlternative="false" seedLimit="1296" cropLimit="1440"/> <!-- Seed: Golden Cobol -->
	<seed id="5225" level="46" cropId="5084" matureId="5114" reward1="1866" reward2="1885" castleId="6" isAlternative="false" seedLimit="1296" cropLimit="1440"/> <!-- Seed: Great Cobol -->
	<seed id="5226" level="49" cropId="5088" matureId="5118" reward1="1867" reward2="4043" castleId="6" isAlternative="false" seedLimit="1620" cropLimit="1800"/> <!-- Seed: Red Codran -->
