=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/xsd/multisell.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="0">
				<xs:element maxOccurs="unbounded" name="item">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element maxOccurs="unbounded" name="ingredient">
									<xs:complexType>
										<xs:attribute name="id" type="xs:unsignedShort" use="required" />
										<xs:attribute name="count" type="xs:unsignedInt" use="required" />
										<xs:attribute name="isTaxIngredient" type="xs:boolean" use="optional" />
										<xs:attribute name="mantainIngredient" type="xs:boolean" use="optional" />
										<xs:attribute name="enchant" type="xs:unsignedByte" use="optional" />
									</xs:complexType>
								</xs:element>
								<xs:element name="production">
									<xs:complexType>
										<xs:attribute name="id" type="xs:unsignedShort" use="required" />
										<xs:attribute name="count" type="xs:unsignedInt" use="required" />
										<xs:attribute name="enchant" type="xs:unsignedByte" use="optional" />
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedShort" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="maintainEnchantment" type="xs:boolean" use="optional" />
			<xs:attribute name="applyTaxes" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/multisell/9150.xml
<?xml version='1.0' encoding='utf-8'?>

<!-- B-Grade Jewels -->

<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">

	<!-- Red Soul Crystal - Stage 1 -->
	<item id="1">
		<ingredient id="4037" count="10000"/>
		<production id="4630" count="1"/>
	</item>

	<!-- Red Soul Crystal - Stage 2 -->
	<item id="2">
		<ingredient id="4037" count="10000"/>
		<production id="4631" count="1"/>
	</item>

	<!-- Red Soul Crystal - Stage 3 -->
	<item id="3">
		<ingredient id="4037" count="10000"/>
		<production id="4632" count="1"/>
	</item>

	<!-- Red Soul Crystal - Stage 4 -->
	<item id="3">
		<ingredient id="4037" count="10000"/>
		<production id="4633" count="1"/>
	</item>

	<!-- Red Soul Crystal - Stage 5 -->
	<item id="4">
		<ingredient id="4037" count="10000"/>
		<production id="4634" count="1"/>
	</item>

	<!-- Red Soul Crystal - Stage 6 -->
	<item id="5">
		<ingredient id="4037" count="10000"/>
		<production id="4635" count="1"/>
	</item>

	<!-- Red Soul Crystal - Stage 11 -->
	<item id="6">
		<ingredient id="4037" count="10000"/>
		<production id="5577" count="1"/>
	</item>

	<!-- Red Soul Crystal - Stage 12 -->
	<item id="7">
		<ingredient id="4037" count="10000"/>
		<production id="5580" count="1"/>
	</item>

	<!-- Green Soul Crystal - Stage 1 -->
	<item id="8">
		<ingredient id="4037" count="10000"/>
		<production id="4641" count="1"/>
	</item>

	<!-- Green Soul Crystal - Stage 2 -->
	<item id="9">
		<ingredient id="4037" count="10000"/>
		<production id="4642" count="1"/>
	</item>

	<!-- Green Soul Crystal - Stage 3 -->
	<item id="10">
		<ingredient id="4037" count="10000"/>
		<production id="4643" count="1"/>
	</item>

	<!-- Green Soul Crystal - Stage 4 -->
	<item id="11">
		<ingredient id="4037" count="10000"/>
		<production id="4644" count="1"/>
	</item>

	<!-- Green Soul Crystal - Stage 5 -->
	<item id="12">
		<ingredient id="4037" count="10000"/>
		<production id="4645" count="1"/>
	</item>

	<!-- Green Soul Crystal - Stage 6 -->
	<item id="13">
		<ingredient id="4037" count="10000"/>
		<production id="4646" count="1"/>
	</item>

	<!-- Green Soul Crystal - Stage 11 -->
	<item id="14">
		<ingredient id="4037" count="10000"/>
		<production id="5578" count="1"/>
	</item>

	<!-- Green Soul Crystal - Stage 12 -->
	<item id="15">
		<ingredient id="4037" count="10000"/>
		<production id="5581" count="1"/>
	</item>

	<!-- Blue Soul Crystal - Stage 1 -->
	<item id="16">
		<ingredient id="4037" count="10000"/>
		<production id="4652" count="1"/>
	</item>

	<!-- Blue Soul Crystal - Stage 2 -->
	<item id="17">
		<ingredient id="4037" count="10000"/>
		<production id="4653" count="1"/>
	</item>

	<!-- Blue Soul Crystal - Stage 3 -->
	<item id="18">
		<ingredient id="4037" count="10000"/>
		<production id="4654" count="1"/>
	</item>

	<!-- Blue Soul Crystal - Stage 4 -->
	<item id="19">
		<ingredient id="4037" count="10000"/>
		<production id="4655" count="1"/>
	</item>

	<!-- Blue Soul Crystal - Stage 5 -->
	<item id="20">
		<ingredient id="4037" count="10000"/>
		<production id="4656" count="1"/>
	</item>

	<!-- Blue Soul Crystal - Stage 6 -->
	<item id="21">
		<ingredient id="4037" count="10000"/>
		<production id="4657" count="1"/>
	</item>

	<!-- Blue Soul Crystal - Stage 11 -->
	<item id="22">
		<ingredient id="4037" count="10000"/>
		<production id="5579" count="1"/>
	</item>

	<!-- Blue Soul Crystal - Stage 12 -->
	<item id="23">
		<ingredient id="4037" count="10000"/>
		<production id="5582" count="1"/>
	</item>

</list>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/multisell/90012.xml
<?xml version='1.0' encoding='utf-8'?>
<!-- Custom GM-Shop -->
<list maintainEnchantment="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<!-- SS/Arrows -->
	<item id="1">
		<ingredient id="4037" count="5" enchant="0"/>
		<production id="4897" count="1" enchant="0"/>
	</item>
	<item id="2">
		<ingredient id="4037" count="5" enchant="0"/>
		<production id="4898" count="1" enchant="0"/>
	</item>
	<item id="3">
		<ingredient id="4037" count="5" enchant="0"/>
		<production id="4899" count="1" enchant="0"/>
	</item>
	<item id="4">
		<ingredient id="4037" count="5" enchant="0"/>
		<production id="4900" count="1" enchant="0"/>
	</item>
	<item id="5">
		<ingredient id="4037" count="5" enchant="0"/>
		<production id="4901" count="1" enchant="0"/>
	</item>
	<item id="6">
		<ingredient id="4037" count="5" enchant="0"/>
		<production id="4902" count="1" enchant="0"/>
	</item>
</list>
