=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/xsd/zones.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="0">
				<xs:element maxOccurs="unbounded" name="zone">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="stat">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="val" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element maxOccurs="unbounded" name="node">
								<xs:complexType>
									<xs:attribute name="X" type="xs:int" use="required" />
									<xs:attribute name="Y" type="xs:int" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="spawn">
								<xs:complexType>
									<xs:attribute name="X" type="xs:int" use="required" />
									<xs:attribute name="Y" type="xs:int" use="required" />
									<xs:attribute name="Z" type="xs:short" use="required" />
									<xs:attribute name="isChaotic" type="xs:boolean" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="shape" type="xs:string" use="required" />
						<xs:attribute name="minZ" type="xs:short" use="required" />
						<xs:attribute name="maxZ" type="xs:short" use="required" />
						<xs:attribute name="id" type="xs:unsignedInt" use="optional" />
						<xs:attribute name="bossId" type="xs:short" use="optional" />
						<xs:attribute name="rad" type="xs:unsignedShort" use="optional" />
						<xs:attribute name="name" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/zones/MotherTreeZone.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- Elven Mother Tree Zones -->
	<zone type="MotherTreeZone" shape="NPoly" minZ="-3550" maxZ="-3350"> <!-- mother_tree_start_zone -->
		<stat name="HpRegenBonus" val="2" />
		<stat name="MpRegenBonus" val="1" />
		<stat name="affectedRace" val="1" /> <!-- Elf -->
		<stat name="enterMsgId" val="114" />
		<stat name="leaveMsgId" val="115" />
		<node X="45889" Y="41890" />
		<node X="45277" Y="41672" />
		<node X="45028" Y="41478" />
		<node X="44809" Y="41230" />
		<node X="44522" Y="40689" />
		<node X="44501" Y="39970" />
		<node X="44725" Y="39407" />
		<node X="44930" Y="39145" />
		<node X="45447" Y="38764" />
		<node X="46073" Y="38618" />
		<node X="46710" Y="38716" />
		<node X="47255" Y="39049" />
		<node X="47743" Y="39834" />
		<node X="47772" Y="40568" />
		<node X="47545" Y="41125" />
		<node X="47108" Y="41599" />
		<node X="46531" Y="41868" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-3121" maxZ="-2921"> <!-- mother_tree_town -->
		<stat name="HpRegenBonus" val="2" />
		<stat name="MpRegenBonus" val="1" />
		<stat name="affectedRace" val="1" /> <!-- Elf -->
		<stat name="enterMsgId" val="114" />
		<stat name="leaveMsgId" val="115" />
		<node X="45234" Y="49892" />
		<node X="45117" Y="49826" />
		<node X="45031" Y="49722" />
		<node X="44986" Y="49597" />
		<node X="44985" Y="49462" />
		<node X="45032" Y="49336" />
		<node X="45116" Y="49233" />
		<node X="45233" Y="49165" />
		<node X="45365" Y="49143" />
		<node X="45498" Y="49166" />
		<node X="45614" Y="49235" />
		<node X="45700" Y="49336" />
		<node X="45746" Y="49462" />
		<node X="45747" Y="49596" />
		<node X="45699" Y="49723" />
		<node X="45614" Y="49825" />
		<node X="45498" Y="49893" />
		<node X="45366" Y="49914" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-3745" maxZ="-3545"> <!-- 20_19_worldtree -->
		<stat name="HpRegenBonus" val="2" />
		<stat name="MpRegenBonus" val="1" />
		<stat name="affectedRace" val="1" /> <!-- Elf -->
		<stat name="enterMsgId" val="114" />
		<stat name="leaveMsgId" val="115" />
		<node X="21101" Y="50538" />
		<node X="21511" Y="50683" />
		<node X="21642" Y="51005" />
		<node X="21583" Y="51349" />
		<node X="21255" Y="51581" />
		<node X="20852" Y="51473" />
		<node X="20627" Y="51121" />
		<node X="20728" Y="50743" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-3260" maxZ="-3060"> <!-- 20_20_worldtree -->
		<stat name="HpRegenBonus" val="2" />
		<stat name="MpRegenBonus" val="1" />
		<stat name="affectedRace" val="1" /> <!-- Elf -->
		<stat name="enterMsgId" val="114" />
		<stat name="leaveMsgId" val="115" />
		<node X="25548" Y="81124" />
		<node X="25660" Y="81548" />
		<node X="25380" Y="81884" />
		<node X="24960" Y="81972" />
		<node X="24660" Y="81716" />
		<node X="24604" Y="81324" />
		<node X="24816" Y="81012" />
		<node X="25248" Y="80944" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-3775" maxZ="-3575"> <!-- 21_20_worldtree -->
		<stat name="HpRegenBonus" val="2" />
		<stat name="MpRegenBonus" val="1" />
		<stat name="affectedRace" val="1" /> <!-- Elf -->
		<stat name="enterMsgId" val="114" />
		<stat name="leaveMsgId" val="115" />
		<node X="57755" Y="85802" />
		<node X="57974" Y="86079" />
		<node X="57953" Y="86404" />
		<node X="57711" Y="86683" />
		<node X="57324" Y="86686" />
		<node X="57105" Y="86436" />
		<node X="57088" Y="86061" />
		<node X="57404" Y="85785" />
	</zone>
	<!-- Oracle of Dusk (Mp Regen Zones) -->
	<zone type="MotherTreeZone" shape="NPoly" minZ="-5168" maxZ="-4968"> <!-- ssq_main_event_17_20_01 -->
		<stat name="MpRegenBonus" val="2" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-79956" Y="84556" />
		<node X="-79832" Y="84620" />
		<node X="-79824" Y="84772" />
		<node X="-79956" Y="84844" />
		<node X="-80080" Y="84772" />
		<node X="-80076" Y="84620" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-5164" maxZ="-4964"> <!-- ssq_main_event_17_20_04 -->
		<stat name="MpRegenBonus" val="2" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-76936" Y="85164" />
		<node X="-76820" Y="85232" />
		<node X="-76816" Y="85380" />
		<node X="-76948" Y="85444" />
		<node X="-77068" Y="85376" />
		<node X="-77068" Y="85236" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-5164" maxZ="-4964"> <!-- ssq_main_event_17_20_05 -->
		<stat name="MpRegenBonus" val="3" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-74924" Y="87012" />
		<node X="-74784" Y="87008" />
		<node X="-74712" Y="87132" />
		<node X="-74780" Y="87256" />
		<node X="-74924" Y="87260" />
		<node X="-75000" Y="87140" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-5176" maxZ="-4976"> <!-- ssq_main_event_17_20_03 -->
		<stat name="MpRegenBonus" val="3" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-77200" Y="88820" />
		<node X="-77076" Y="88896" />
		<node X="-77076" Y="89040" />
		<node X="-77204" Y="89108" />
		<node X="-77328" Y="89044" />
		<node X="-77328" Y="88892" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-5172" maxZ="-4972"> <!-- ssq_main_event_17_20_02 -->
		<stat name="MpRegenBonus" val="4" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-80204" Y="88220" />
		<node X="-80080" Y="88288" />
		<node X="-80080" Y="88428" />
		<node X="-80208" Y="88504" />
		<node X="-80336" Y="88428" />
		<node X="-80328" Y="88292" />
	</zone>
	<!-- Oracle of Dawn (Mp Regen Zones) -->
	<zone type="MotherTreeZone" shape="NPoly" minZ="-4916" maxZ="-4716"> <!-- ssq_main_event_17_21_01 -->
		<stat name="MpRegenBonus" val="2" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-78796" Y="109452" />
		<node X="-78804" Y="109608" />
		<node X="-78924" Y="109672" />
		<node X="-79056" Y="109600" />
		<node X="-79056" Y="109456" />
		<node X="-78932" Y="109380" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-4908" maxZ="-4708"> <!-- ssq_main_event_17_21_02 -->
		<stat name="MpRegenBonus" val="2" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-75920" Y="109992" />
		<node X="-75792" Y="110068" />
		<node X="-75792" Y="110220" />
		<node X="-75912" Y="110288" />
		<node X="-76048" Y="110212" />
		<node X="-76044" Y="110068" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-4916" maxZ="-4716"> <!-- ssq_main_event_17_21_05 -->
		<stat name="MpRegenBonus" val="3" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-73900" Y="111844" />
		<node X="-73752" Y="111840" />
		<node X="-73688" Y="111976" />
		<node X="-73760" Y="112092" />
		<node X="-73904" Y="112092" />
		<node X="-73976" Y="111968" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-4912" maxZ="-4712"> <!-- ssq_main_event_17_21_03 -->
		<stat name="MpRegenBonus" val="3" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-76172" Y="113656" />
		<node X="-76052" Y="113728" />
		<node X="-76048" Y="113872" />
		<node X="-76172" Y="113944" />
		<node X="-76308" Y="113876" />
		<node X="-76304" Y="113728" />
	</zone>
	<zone type="MotherTreeZone" shape="NPoly" minZ="-4908" maxZ="-4708"> <!-- ssq_main_event_17_21_04 -->
		<stat name="MpRegenBonus" val="4" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-79184" Y="113040" />
		<node X="-79060" Y="113116" />
		<node X="-79052" Y="113268" />
		<node X="-79184" Y="113336" />
		<node X="-79304" Y="113260" />
		<node X="-79304" Y="113116" />
	</zone>
	<!-- Devil Isle Zones -->
	<!-- Recovery -->
	<zone type="MotherTreeZone" shape="NPoly" minZ="-3913" maxZ="-3413"> <!-- devil_healing_zone -->
		<stat name="HpRegenBonus" val="2" />
		<stat name="MpRegenBonus" val="1" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="41520" Y="205163" />
		<node X="44448" Y="205623" />
		<node X="44352" Y="208957" />
		<node X="42813" Y="208983" />
		<node X="41473" Y="207893" />
	</zone>
</list>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/zones/ArenaZone.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- PVP Zones -->
	<zone type="ArenaZone" shape="Cuboid" minZ="-3596" maxZ="0"> <!-- dion_monster_pvp -->
		<node X="11947" Y="183019" />
		<node X="12943" Y="184010" />
		<spawn X="12312" Y="182752" Z="-3558" />
	</zone>
	<zone type="ArenaZone" shape="Cuboid" minZ="-3752" maxZ="-352"> <!-- gludin_pvp -->
		<node X="-88411" Y="141732" />
		<node X="-87429" Y="142708" />
		<spawn X="-86979" Y="142402" Z="-3643" />
	</zone>
	<zone type="ArenaZone" shape="Cuboid" minZ="-3850" maxZ="-350"> <!-- giran_pvp_battle -->
		<node X="72493" Y="142263" />
		<node X="73493" Y="143261" />
		<spawn X="73890" Y="142656" Z="-3778" />
	</zone>
	<zone type="ArenaZone" shape="NPoly" minZ="-3498" maxZ="-3298"> <!-- coliseum_battle -->
		<node X="150948" Y="46483" />
		<node X="151210" Y="46186" />
		<node X="151221" Y="45928" />
		<node X="150737" Y="45344" />
		<node X="148265" Y="45346" />
		<node X="147769" Y="45942" />
		<node X="147784" Y="46184" />
		<node X="148047" Y="46482" />
		<node X="148049" Y="46954" />
		<node X="147781" Y="47256" />
		<node X="147769" Y="47492" />
		<node X="148263" Y="48087" />
		<node X="150745" Y="48084" />
		<node X="151220" Y="47493" />
		<node X="151216" Y="47259" />
		<node X="150947" Y="46960" />
		<spawn X="147451" Y="46728" Z="-3410" />
	</zone>
</list>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/zones/FortZone.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- Fortress Zones -->
	<zone id="21501" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Shanty Fortress -->
		<stat name="fortId" val="101" />
		<node X="-56256" Y="153728" />
		<node X="-49536" Y="159424" />
		<spawn X="-52695" Y="156457" Z="-2053" />
	</zone>
	<zone id="21502" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Southern Fortress -->
		<stat name="fortId" val="102" />
		<node X="-26304" Y="216576" />
		<node X="-19584" Y="222912" />
		<spawn X="-22759" Y="219818" Z="-3236" />
	</zone>
	<zone id="21503" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Hive Fortress -->
		<stat name="fortId" val="103" />
		<node X="12544" Y="185856" />
		<node X="19456" Y="190272" />
		<spawn X="16625" Y="188108" Z="-2924" />
	</zone>
	<zone id="21504" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Valley Fortress -->
		<stat name="fortId" val="104" />
		<node X="122432" Y="120192" />
		<node X="129600" Y="126656" />
		<spawn X="126058" Y="123425" Z="-2585" />
	</zone>
	<zone id="21505" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Ivory Fortress -->
		<stat name="fortId" val="105" />
		<node X="70080" Y="1984" />
		<node X="74944" Y="6656" />
		<spawn X="72808" Y="4307" Z="-3045" />
	</zone>
	<zone id="21506" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Narsell Fortress -->
		<stat name="fortId" val="106" />
		<node X="151936" Y="52736" />
		<node X="157760" Y="58304" />
		<spawn X="154966" Y="55276" Z="-3254" />
	</zone>
	<zone id="21507" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Bayou Fortress -->
		<stat name="fortId" val="107" />
		<node X="186368" Y="36288" />
		<node X="192640" Y="42240" />
		<spawn X="189910" Y="39770" Z="-3410" />
	</zone>
	<zone id="21508" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- White Sands Fortress -->
		<stat name="fortId" val="108" />
		<node X="114432" Y="201664" />
		<node X="122176" Y="208704" />
		<spawn X="118361" Y="204924" Z="-3333" />
	</zone>
	<zone id="21509" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Borderland Fortress -->
		<stat name="fortId" val="109" />
		<node X="155776" Y="-72896" />
		<node X="162368" Y="-67776" />
		<spawn X="159009" Y="-70167" Z="-2864" />
	</zone>
	<zone id="21510" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Marshland Fortress -->
		<stat name="fortId" val="110" />
		<node X="66304" Y="-63872" />
		<node X="72832" Y="-58688" />
		<spawn X="69791" Y="-61482" Z="-2786" />
	</zone>
	<zone id="21511" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Archaic Fortress -->
		<stat name="fortId" val="111" />
		<node X="106176" Y="-143616" />
		<node X="112704" Y="-138752" />
		<spawn X="109568" Y="-141277" Z="-2957" />
	</zone>
	<zone id="21512" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Floran Fortress - Border -->
		<stat name="fortId" val="112" />
		<node X="1472" Y="145216" />
		<node X="9728" Y="155136" />
		<spawn X="5688" Y="149726" Z="-2889" />
	</zone>
	<zone id="21513" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Cloud Mountain Fortress - Border -->
		<stat name="fortId" val="113" />
		<node X="-57408" Y="88704" />
		<node X="-49408" Y="93824" />
		<spawn X="-53204" Y="91210" Z="-2821" />
	</zone>
	<zone id="21514" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Tanor Fortress - Border -->
		<stat name="fortId" val="114" />
		<node X="56256" Y="136768" />
		<node X="64256" Y="142016" />
		<spawn X="60258" Y="139425" Z="-1754" />
	</zone>
	<zone id="21515" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Dragonspine Fortress - Border -->
		<stat name="fortId" val="115" />
		<node X="8000" Y="92928" />
		<node X="14976" Y="97408" />
		<spawn X="11542" Y="95060" Z="-3426" />
	</zone>
	<zone id="21516" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Antharas Fortress - Border -->
		<stat name="fortId" val="116" />
		<node X="75904" Y="86336" />
		<node X="80448" Y="95488" />
		<spawn X="79199" Y="91021" Z="-2878" />
	</zone>
	<zone id="21517" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Western Fortress - Border -->
		<stat name="fortId" val="117" />
		<node X="107264" Y="-17664" />
		<node X="115392" Y="-12544" />
		<spawn X="111376" Y="-15203" Z="-995" />
	</zone>
	<zone id="21518" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Hunters Fortress - Border -->
		<stat name="fortId" val="118" />
		<node X="121472" Y="92992" />
		<node X="129088" Y="97792" />
		<spawn X="125308" Y="95066" Z="-2140" />
	</zone>
	<zone id="21519" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Aaru Fortress - Border -->
		<stat name="fortId" val="119" />
		<node X="69120" Y="182400" />
		<node X="76672" Y="190784" />
		<spawn X="73066" Y="185954" Z="-2581" />
	</zone>
	<zone id="21520" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Demon Fortress - Border -->
		<stat name="fortId" val="120" />
		<node X="98432" Y="-56465" />
		<node X="102912" Y="-52288" />
		<spawn X="100698" Y="-55334" Z="-645" />
	</zone>
	<zone id="21521" type="FortZone" shape="Cuboid" minZ="-3800" maxZ="3200">
		<!-- Monastic Fortress - Border -->
		<stat name="fortId" val="121" />
		<node X="68480" Y="-97536" />
		<node X="75520" Y="-92224" />
		<spawn X="72146" Y="-94782" Z="-1428" />
	</zone>
</list>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/zones/SwampZone.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- Swamp Zones -->
	<zone type="SwampZone" shape="NPoly" minZ="-3964" maxZ="-3364"> <!-- devil_slow_8 -->
		<!-- stat name="initialDelay" val="1000" / -->
		<stat name="move_bonus" val="-80" />
		<node X="55250" Y="210873" />
		<node X="55762" Y="211217" />
		<node X="55934" Y="212274" />
		<node X="55686" Y="212533" />
		<node X="54639" Y="212740" />
		<node X="54276" Y="212407" />
		<node X="54160" Y="211696" />
		<node X="54332" Y="211108" />
	</zone>
	<!-- Sea of Spores (Swamp Zone) -->
	<zone type="SwampZone" shape="NPoly" minZ="-4468" maxZ="-4118"> <!-- spore_boss_swamp_zone -->
		<node X="43084" Y="15944" />
		<node X="45140" Y="15816" />
		<node X="45748" Y="17200" />
		<node X="44504" Y="18780" />
		<node X="43284" Y="18952" />
		<node X="42476" Y="18164" />
		<node X="42480" Y="16448" />
	</zone>
</list>
