=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/xsd/zones.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="0">
				<xs:element maxOccurs="unbounded" name="zone">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="stat">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="val" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element maxOccurs="unbounded" name="node">
								<xs:complexType>
									<xs:attribute name="X" type="xs:int" use="required" />
									<xs:attribute name="Y" type="xs:int" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="spawn">
								<xs:complexType>
									<xs:attribute name="X" type="xs:int" use="required" />
									<xs:attribute name="Y" type="xs:int" use="required" />
									<xs:attribute name="Z" type="xs:short" use="required" />
									<xs:attribute name="isChaotic" type="xs:boolean" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="shape" type="xs:string" use="required" />
						<xs:attribute name="minZ" type="xs:short" use="required" />
						<xs:attribute name="maxZ" type="xs:short" use="required" />
						<xs:attribute name="id" type="xs:unsignedInt" use="optional" />
						<xs:attribute name="bossId" type="xs:short" use="optional" />
						<xs:attribute name="rad" type="xs:unsignedShort" use="optional" />
						<xs:attribute name="name" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/zones/BossZone.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- Boss zone Four Sepulchers -->
	<zone id="12002" type="BossZone" shape="Cuboid" minZ="-7350" maxZ="-6841" bossId="-1">
		<stat name="name" val="Four Sepulcher" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="300000" />
		<node X="181241" Y="-86443" />
		<node X="192134" Y="-84575" />
	</zone>
	<!-- Boss zone Four Sepulchers -->
	<zone id="12003" type="BossZone" shape="Cuboid" minZ="-7350" maxZ="-6841" bossId="-1">
		<stat name="name" val="Four Sepulcher" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="300000" />
		<node X="179551" Y="-89844" />
		<node X="190342" Y="-88042" />
	</zone>
	<!-- Boss zone Four Sepulchers -->
	<zone id="12004" type="BossZone" shape="Cuboid" minZ="-7350" maxZ="-6841" bossId="-1">
		<stat name="name" val="Four Sepulcher" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="300000" />
		<node X="172354" Y="-86630" />
		<node X="174073" Y="-75565" />
	</zone>
	<!-- Boss zone Four Sepulchers -->
	<zone id="12005" type="BossZone" shape="Cuboid" minZ="-7350" maxZ="-6841" bossId="-1">
		<stat name="name" val="Four Sepulcher" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="300000" />
		<node X="174697" Y="-82707" />
		<node X="176500" Y="-71885" />
	</zone>
	<!-- Boss zone Lair of Antharas -->
	<zone id="12006" type="BossZone" shape="Cuboid" minZ="-8220" maxZ="-4870" bossId="29019">
		<stat name="name" val="Lair of Antharas" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="600000" />
		<node X="173439" Y="110176" />
		<node X="187346" Y="119469" />
	</zone>
	<!-- Boss zone Lair of Baium -->
	<zone id="12007" type="BossZone" shape="NPoly" minZ="9967" maxZ="16301" bossId="29020">
		<stat name="name" val="Lair of Baium" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="600000" />
		<node X="112987" Y="14312" />
		<node X="112507" Y="14623" />
		<node X="112129" Y="15551" />
		<node X="111890" Y="16230" />
		<node X="112067" Y="16965" />
		<node X="112496" Y="17482" />
		<node X="112863" Y="18120" />
		<node X="113453" Y="18561" />
		<node X="114135" Y="18590" />
		<node X="114815" Y="18811" />
		<node X="115549" Y="18648" />
		<node X="116074" Y="18205" />
		<node X="116776" Y="17506" />
		<node X="117255" Y="17013" />
		<node X="117371" Y="16298" />
		<node X="117405" Y="15925" />
		<node X="117236" Y="15199" />
		<node X="117158" Y="14895" />
		<node X="116784" Y="14260" />
		<node X="116096" Y="13902" />
		<node X="115159" Y="13507" />
		<node X="114135" Y="13518" />
		<node X="113203" Y="13898" />
	</zone>
	<!-- Boss zone Lair of Valakas -->
	<zone id="12008" type="BossZone" shape="Cuboid" minZ="-1735" maxZ="16301" bossId="29028">
		<stat name="name" val="Lair of Valakas" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="1800000" />
		<node X="199755" Y="-124724" />
		<node X="224677" Y="-103211" />
	</zone>
	<!-- Boss zone Lair of Lilith -->
	<zone id="12009" type="BossZone" shape="Cuboid" minZ="-5600" maxZ="-3895" bossId="25283">
		<stat name="name" val="Lair of Lilith" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="1800000" />
		<node X="183986" Y="-13716" />
		<node X="186097" Y="-11532" />
	</zone>
	<!-- Boss zone Lair of Anakim -->
	<zone id="12010" type="BossZone" shape="Cuboid" minZ="-5600" maxZ="-3895" bossId="25286">
		<stat name="name" val="Lair of Anakim" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="1800000" />
		<node X="184008" Y="-10681" />
		<node X="186107" Y="-8589" />
	</zone>
	<!-- Boss zone Lair of Zaken -->
	<zone id="12011" type="BossZone" shape="Cuboid" minZ="-3775" maxZ="-2690" bossId="29022">
		<stat name="name" val="Lair of Zaken" />
		<stat name="Flying" val="false" />
		<stat name="EnabledByDefault" val="false" />
		<stat name="InvadeTime" val="1800000" />
		<node X="53182" Y="216945" />
		<node X="57311" Y="221151" />
	</zone>
	<!-- Boss zone SunlightRoom -->
	<zone id="12012" type="BossZone" shape="Cuboid" minZ="-2900" maxZ="-2690" bossId="-1">
		<stat name="name" val="Sunlight Room" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="0" />
		<node X="55794" Y="219633" />
		<node X="56789" Y="220629" />
	</zone>
	<!-- Boss zone Lair of Sailren -->
	<zone id="12013" type="BossZone" shape="Cuboid" minZ="-2075" maxZ="-1944" bossId="29065">
		<stat name="name" val="Lair of Sailren" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="0" />
		<node X="26095" Y="-8084" />
		<node X="28987" Y="-5295" />
	</zone>
	<!-- Boss zone AltarofSacrifice -->
	<zone id="12014" type="BossZone" shape="Cuboid" minZ="-10730" maxZ="-10290" bossId="-1">
		<stat name="name" val="Altar of Sacrifice" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="0" />
		<node X="-18176" Y="-54972" />
		<node X="-14614" Y="-51620" />
	</zone>
	<!-- Boss zone Lair of Ice Fairy Sirra -->
	<zone id="12015" type="BossZone" shape="NPoly" minZ="-30000" maxZ="30000" bossId="29056">
		<stat name="name" val="Ice Queen Castle" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="0" />
		<node X="114473" Y="-125909" />
		<node X="112930" Y="-128454" />
		<node X="112531" Y="-128878" />
		<node X="111686" Y="-129216" />
		<node X="111139" Y="-129870" />
		<node X="109445" Y="-130222" />
		<node X="108833" Y="-130162" />
		<node X="107534" Y="-129789" />
		<node X="106529" Y="-130047" />
		<node X="104340" Y="-129183" />
		<node X="103691" Y="-128671" />
		<node X="102912" Y="-128649" />
		<node X="101967" Y="-128170" />
		<node X="100645" Y="-126865" />
		<node X="100164" Y="-125878" />
		<node X="100430" Y="-125058" />
		<node X="100997" Y="-124231" />
		<node X="101570" Y="-123264" />
		<node X="102569" Y="-122852" />
		<node X="103934" Y="-123152" />
		<node X="104984" Y="-123806" />
		<node X="107116" Y="-124592" />
		<node X="107995" Y="-124541" />
		<node X="108432" Y="-124602" />
		<node X="109241" Y="-124654" />
		<node X="110081" Y="-124903" />
		<node X="110600" Y="-125052" />
		<node X="112720" Y="-125225" />
	</zone>
	<!-- Boss zone Frintezza -->
	<zone id="12016" type="BossZone" shape="Cuboid" minZ="-6130" maxZ="-3000" bossId="29047">
		<stat name="name" val="Last Imperial Tomb" />
		<stat name="Flying" val="false" />
		<stat name="InvadeTime" val="1800000" />
		<node X="172176" Y="-74106" />
		<node X="175984" Y="-90033" />
	</zone>
	<!-- Boss zone Lair of Orfen -->
	<zone id="12018" type="BossZone" shape="NPoly" minZ="-5796" maxZ="-3796" bossId="29014">
		<stat name="name" val="Lair of Orfen" />
		<stat name="EnabledByDefault" val="false" />
		<stat name="InvadeTime" val="0" />
		<node X="43976" Y="24664" />
		<node X="43284" Y="18952" />
		<node X="42476" Y="18164" />
		<node X="42480" Y="16448" />
		<node X="43084" Y="15944" />
		<node X="45140" Y="15816" />
		<node X="48800" Y="15112" />
		<node X="56556" Y="12040" />
		<node X="59068" Y="14288" />
		<node X="61064" Y="18492" />
		<node X="60380" Y="23672" />
		<node X="58724" Y="27412" />
		<node X="55696" Y="28496" />
		<node X="43976" Y="24664" />
	</zone>
	<!-- Boss zone Lair of Ant Queen -->
	<zone id="12019" type="BossZone" shape="NPoly" minZ="-5947" maxZ="-5547" bossId="29001">
		<stat name="name" val="Lair of Ant Queen" />
		<stat name="EnabledByDefault" val="false" />
		<stat name="InvadeTime" val="0" />
		<node X="-21490" Y="178613" />
		<node X="-22258" Y="178961" />
		<node X="-22890" Y="182205" />
		<node X="-22770" Y="183129" />
		<node X="-21594" Y="183945" />
		<node X="-20570" Y="183381" />
		<node X="-20310" Y="182673" />
		<node X="-20762" Y="179129" />
	</zone>
</list>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/zones/NoStoreZone.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- CUSTOM - NO STORE ZONES -->
	<!-- Giran - northern coridor - west -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3400" maxZ="-3550">
		<node X="81446" Y="143530" />
		<node X="81635" Y="147720" />
	</zone>
	<!-- Giran - northern coridor - east -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3350" maxZ="-3450">
		<node X="83790" Y="143495" />
		<node X="84000" Y="147230" />
	</zone>
	<!-- Giran - western coridor (up to the Dusk Priestess) -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3650" maxZ="-3400">
		<node X="77080" Y="148525" />
		<node X="81780" Y="148720" />
	</zone>
	<!-- Giran - southern coridor -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3550" maxZ="-3400">
		<node X="81435" Y="149530" />
		<node X="81640" Y="152920" />
	</zone>
	<!-- Giran - northern path -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3500" maxZ="-3400">
		<node X="80930" Y="147680" />
		<node X="82940" Y="147875" />
	</zone>
	<!-- Giran - western path -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3500" maxZ="-3400">
		<node X="80930" Y="147680" />
		<node X="81115" Y="149540" />
	</zone>
	<!-- Giran - southern path -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3500" maxZ="-3400">
		<node X="80925" Y="149340" />
		<node X="82940" Y="149535" />
	</zone>
	<!-- Giran - large temple area (gatekeeper and Priest of Dawn area) -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3500" maxZ="-3350">
		<node X="82735" Y="147000" />
		<node X="84320" Y="149780" />
	</zone>
	<!-- Giran - olympiad manager -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3500" maxZ="-3400">
		<node X="81985" Y="147450" />
		<node X="82205" Y="147710" />
	</zone>
	<!-- Giran - manor manager -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3500" maxZ="-3400">
		<node X="81865" Y="149530" />
		<node X="82030" Y="149680" />
	</zone>
	<!-- Giran - auctioneer and gabrielle -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3500" maxZ="-3400">
		<node X="81205" Y="149520" />
		<node X="81510" Y="149830" />
	</zone>
	<!-- Giran - path to taurin -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3550" maxZ="-3450">
		<node X="81055" Y="146820" />
		<node X="81455" Y="147000" />
	</zone>
	<!-- Giran - path to warehouse -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3550" maxZ="-3450">
		<node X="81620" Y="146465" />
		<node X="82035" Y="146680" />
	</zone>
	<!-- Giran - Taurin -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3550" maxZ="-3450">
		<node X="80655" Y="146350" />
		<node X="80855" Y="146460" />
	</zone>
	<!-- Giran - Collob -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-3550" maxZ="-3450">
		<node X="79200" Y="149455" />
		<node X="79300" Y="149645" />
	</zone>
	<!-- Aden - olympiad manager square -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-2250" maxZ="-2150">
		<node X="146841" Y="26541" />
		<node X="148071" Y="27425" />
	</zone>
	<!-- Aden - central stairs -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-2250" maxZ="-1950">
		<node X="147273" Y="25941" />
		<node X="147645" Y="26538" />
	</zone>
	<!-- Aden - temple square -->
	<zone type="NoStoreZone" shape="Cuboid" minZ="-2050" maxZ="-1950">
		<node X="146233" Y="25938" />
		<node X="148729" Y="25553" />
	</zone>
</list>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/zones/CastleZone.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- Castle Zones -->
	<zone id="11200" type="CastleZone" shape="NPoly" minZ="-4448" maxZ="3551"> <!-- gludio_castle -->
		<stat name="castleId" val="1" />
		<node X="-22615" Y="104510" />
		<node X="-13290" Y="104564" />
		<node X="-13313" Y="116950" />
		<node X="-22638" Y="116896" />
		<!-- banish_point_list -->
		<spawn X="-15881" Y="110651" Z="-2770" isChaotic="true" />
		<spawn X="-15679" Y="110168" Z="-2770" isChaotic="true" />
		<spawn X="-15553" Y="110780" Z="-2770" isChaotic="true" />
		<spawn X="-15281" Y="110142" Z="-2770" isChaotic="true" />
		<!-- owner_restart_point_list -->
		<spawn X="-16554" Y="109382" Z="-1799" />
		<spawn X="-16869" Y="109375" Z="-1799" />
		<spawn X="-16659" Y="109261" Z="-1799" />
		<spawn X="-16618" Y="109485" Z="-1799" />
	</zone>
	<zone id="11201" type="CastleZone" shape="NPoly" minZ="-4642" maxZ="4000"> <!-- dion_castle -->
		<stat name="castleId" val="2" />
		<node X="26575" Y="165240" />
		<node X="17250" Y="165186" />
		<node X="17273" Y="152800" />
		<node X="26598" Y="152854" />
		<!-- banish_point_list -->
		<spawn X="19852" Y="159170" Z="-2770" isChaotic="true" />
		<spawn X="19650" Y="159653" Z="-2770" isChaotic="true" />
		<spawn X="19524" Y="159041" Z="-2770" isChaotic="true" />
		<spawn X="19252" Y="159679" Z="-2770" isChaotic="true" />
		<!-- owner_restart_point_list -->
		<spawn X="20514" Y="160368" Z="-1993" />
		<spawn X="20829" Y="160375" Z="-1993" />
		<spawn X="20619" Y="160489" Z="-1993" />
		<spawn X="20578" Y="160265" Z="-1993" />
	</zone>
	<zone id="11202" type="CastleZone" shape="NPoly" minZ="-4515" maxZ="19935"> <!-- giran_castle -->
		<stat name="castleId" val="3" />
		<node X="121412" Y="140594" />
		<node X="121358" Y="149919" />
		<node X="108972" Y="149896" />
		<node X="109026" Y="140571" />
		<!-- banish_point_list -->
		<spawn X="115275" Y="147273" Z="-2770" isChaotic="true" />
		<spawn X="115758" Y="147475" Z="-2770" isChaotic="true" />
		<spawn X="115146" Y="147601" Z="-2770" isChaotic="true" />
		<spawn X="115784" Y="147873" Z="-2770" isChaotic="true" />
		<!-- owner_restart_point_list -->
		<spawn X="116540" Y="146655" Z="-1866" />
		<spawn X="116547" Y="146340" Z="-1866" />
		<spawn X="116661" Y="146550" Z="-1866" />
		<spawn X="116437" Y="146591" Z="-1866" />
	</zone>
	<zone id="11203" type="CastleZone" shape="NPoly" minZ="-4242" maxZ="19935"> <!-- oren_castle -->
		<stat name="castleId" val="4" />
		<node X="87488" Y="32689" />
		<node X="87434" Y="42014" />
		<node X="75048" Y="41991" />
		<node X="75102" Y="32666" />
		<!-- banish_point_list -->
		<spawn X="81353" Y="39421" Z="-2770" isChaotic="true" />
		<spawn X="81836" Y="39623" Z="-2770" isChaotic="true" />
		<spawn X="81224" Y="39749" Z="-2770" isChaotic="true" />
		<spawn X="81862" Y="40021" Z="-2770" isChaotic="true" />
		<!-- owner_restart_point_list -->
		<spawn X="82616" Y="38750" Z="-1593" />
		<spawn X="82623" Y="38435" Z="-1593" />
		<spawn X="82737" Y="38645" Z="-1593" />
		<spawn X="82513" Y="38686" Z="-1593" />
	</zone>
	<zone id="11204" type="CastleZone" shape="NPoly" minZ="-3184" maxZ="6816"> <!-- aden_castle -->
		<stat name="castleId" val="5" />
		<node X="142431" Y="362" />
		<node X="152319" Y="344" />
		<node X="152282" Y="15197" />
		<node X="142393" Y="15215" />
		<!-- banish_point_list -->
		<spawn X="151765" Y="4175" Z="-592" isChaotic="true" />
		<spawn X="151555" Y="2660" Z="-592" isChaotic="true" />
		<spawn X="151065" Y="1813" Z="-592" isChaotic="true" />
		<spawn X="150952" Y="2615" Z="-592" isChaotic="true" />
		<!-- owner_restart_point_list -->
		<spawn X="147700" Y="4608" Z="-2784" />
		<spawn X="147705" Y="4865" Z="-2784" />
		<spawn X="147200" Y="4865" Z="-2784" />
		<spawn X="147200" Y="4350" Z="-2784" />
		<spawn X="147705" Y="4350" Z="-2784" />
	</zone>
	<zone id="11205" type="CastleZone" shape="NPoly" minZ="-2738" maxZ="4000"> <!-- innadrile_castle -->
		<stat name="castleId" val="6" />
		<node X="120526" Y="254019" />
		<node X="111201" Y="253965" />
		<node X="111224" Y="241579" />
		<node X="120549" Y="241633" />
		<!-- banish_point_list -->
		<spawn X="118730" Y="243416" Z="-1060" isChaotic="true" />
		<spawn X="118932" Y="242933" Z="-1060" isChaotic="true" />
		<spawn X="119058" Y="243545" Z="-1060" isChaotic="true" />
		<spawn X="119330" Y="242907" Z="-1060" isChaotic="true" />
		<!-- owner_restart_point_list -->
		<spawn X="114465" Y="249147" Z="-89" />
		<spawn X="114780" Y="249154" Z="-89" />
		<spawn X="114570" Y="249268" Z="-89" />
		<spawn X="114529" Y="249044" Z="-89" />
	</zone>
	<zone id="11206" type="CastleZone" shape="NPoly" minZ="-3397" maxZ="2103"> <!-- goddard_castle -->
		<stat name="castleId" val="7" />
		<node X="141457" Y="-51510" />
		<node X="151949" Y="-51510" />
		<node X="151949" Y="-39107" />
		<node X="145899" Y="-39107" />
		<node X="141457" Y="-44407" />
		<!-- banish_point_list -->
		<spawn X="154848" Y="-52608" Z="-2962" isChaotic="true" />
		<spawn X="156400" Y="-53808" Z="-2873" isChaotic="true" />
		<spawn X="138439" Y="-45153" Z="-2064" isChaotic="true" />
		<spawn X="140871" Y="-55380" Z="-3224" isChaotic="true" />
		<!-- owner_restart_point_list -->
		<spawn X="147408" Y="-46448" Z="-963" />
		<spawn X="147520" Y="-46432" Z="-963" />
		<spawn X="147408" Y="-46896" Z="-963" />
		<spawn X="147536" Y="-46896" Z="-963" />
	</zone>
	<zone id="11207" type="CastleZone" shape="Cuboid" minZ="-3000" maxZ="20000"> <!-- rune_castle -->
		<stat name="castleId" val="8" />
		<node X="7000" Y="-55500" />
		<node X="27250" Y="-41716" />
		<!-- banish_point_list -->
		<spawn X="38096" Y="-46976" Z="899" isChaotic="true" />
		<spawn X="38608" Y="-47168" Z="899" isChaotic="true" />
		<spawn X="38752" Y="-47792" Z="899" isChaotic="true" />
		<spawn X="38848" Y="-48640" Z="899" isChaotic="true" />
		<!-- owner_restart_point_list -->
		<spawn X="10891" Y="-49058" Z="3890" />
		<spawn X="11224" Y="-49116" Z="3890" />
		<spawn X="10974" Y="-49244" Z="3890" />
		<spawn X="10658" Y="-49211" Z="3890" />
	</zone>
	<zone id="11208" type="CastleZone" shape="Cuboid" minZ="-3800" maxZ="20000"> <!-- schuttgart_castle -->
		<stat name="castleId" val="9" />
		<node X="73000" Y="-156600" />
		<node X="82560" Y="-144750" />
		<!-- banish_point_list -->
		<spawn X="76131" Y="-145636" Z="-1200" isChaotic="true" />
		<spawn X="76298" Y="-145760" Z="-1184" isChaotic="true" />
		<spawn X="76319" Y="-145530" Z="-1208" isChaotic="true" />
		<spawn X="76104" Y="-145158" Z="-1264" isChaotic="true" />
		<!-- owner_restart_point_list -->
		<spawn X="77619" Y="-150591" Z="770" />
		<spawn X="77487" Y="-150735" Z="770" />
		<spawn X="77575" Y="-150992" Z="770" />
		<spawn X="77646" Y="-150441" Z="770" />
	</zone>
</list>

=== Hl4p3x/L2JServer_C6_Interlude/dist/game/data/zones/HqZone.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- Castle HQ Zones -->
	<!-- Gludio Casle HQ Zones -->
	<zone type="HqZone" shape="NPoly" minZ="-4484" maxZ="3515"> <!-- gludio_castle_headquarter_territory1 -->
		<!-- headquarter_territory -->
		<node X="-22052" Y="114025" />
		<node X="-14221" Y="114007" />
		<node X="-14197" Y="116558" />
		<node X="-22032" Y="116566" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-4420" maxZ="3579"> <!-- gludio_castle_headquarter_territory2 -->
		<!-- headquarter_territory -->
		<node X="-22030" Y="104809" />
		<node X="-20270" Y="104817" />
		<node X="-20266" Y="113735" />
		<node X="-22031" Y="113732" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-4388" maxZ="3611"> <!-- gludio_castle_headquarter_territory3 -->
		<!-- headquarter_territory -->
		<node X="-15554" Y="104834" />
		<node X="-13917" Y="104839" />
		<node X="-13914" Y="113757" />
		<node X="-15554" Y="113757" />
	</zone>
	<!-- Dion Castle HQ Zones -->
	<zone type="HqZone" shape="NPoly" minZ="-4678" maxZ="4000"> <!-- dion_castle_headquarter_territory1 -->
		<!-- headquarter_territory -->
		<node X="26012" Y="155725" />
		<node X="18181" Y="155743" />
		<node X="18157" Y="153192" />
		<node X="25992" Y="153184" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-4614" maxZ="4000"> <!-- dion_castle_headquarter_territory2 -->
		<!-- headquarter_territory -->
		<node X="25990" Y="164941" />
		<node X="24230" Y="164933" />
		<node X="24226" Y="156015" />
		<node X="25991" Y="156018" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-4582" maxZ="4000"> <!-- dion_castle_headquarter_territory3 -->
		<!-- headquarter_territory -->
		<node X="19514" Y="164916" />
		<node X="17877" Y="164911" />
		<node X="17874" Y="155993" />
		<node X="19514" Y="155993" />
	</zone>
	<!-- Giran Castle HQ Zones -->
	<zone type="HqZone" shape="NPoly" minZ="-4551" maxZ="19899"> <!-- giran_castle_headquarter_territory1 -->
		<!-- headquarter_territory -->
		<node X="111897" Y="141157" />
		<node X="111915" Y="148988" />
		<node X="109364" Y="149012" />
		<node X="109356" Y="141177" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-4487" maxZ="19963"> <!-- giran_castle_headquarter_territory2 -->
		<!-- headquarter_territory -->
		<node X="121113" Y="141179" />
		<node X="121105" Y="142939" />
		<node X="112187" Y="142943" />
		<node X="112190" Y="141178" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-4455" maxZ="19995"> <!-- giran_castle_headquarter_territory3 -->
		<!-- headquarter_territory -->
		<node X="121088" Y="147655" />
		<node X="121083" Y="149292" />
		<node X="112165" Y="149295" />
		<node X="112165" Y="147655" />
	</zone>
	<!-- Oren Castle HQ Zones -->
	<zone type="HqZone" shape="NPoly" minZ="-4278" maxZ="19899"> <!-- oren_castle_headquarter_territory1 -->
		<!-- headquarter_territory -->
		<node X="77973" Y="33252" />
		<node X="77991" Y="41083" />
		<node X="75440" Y="41107" />
		<node X="75432" Y="33272" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-4214" maxZ="19963"> <!-- oren_castle_headquarter_territory2 -->
		<!-- headquarter_territory -->
		<node X="87189" Y="33274" />
		<node X="87181" Y="35034" />
		<node X="78263" Y="35038" />
		<node X="78266" Y="33273" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-4182" maxZ="19995"> <!-- oren_castle_headquarter_territory3 -->
		<!-- headquarter_territory -->
		<node X="87164" Y="39750" />
		<node X="87159" Y="41387" />
		<node X="78241" Y="41390" />
		<node X="78241" Y="39750" />
	</zone>
	<!-- Aden Castle HQ Zones -->
	<zone type="HqZone" shape="NPoly" minZ="-1158" maxZ="42"> <!-- aden_castle_headquarter_territory -->
		<!-- headquarter_territory -->
		<node X="144365" Y="9902" />
		<node X="150572" Y="9919" />
		<node X="150816" Y="4925" />
		<node X="151831" Y="4916" />
		<node X="151833" Y="7955" />
		<node X="150754" Y="9839" />
		<node X="150281" Y="10385" />
		<node X="151282" Y="12184" />
		<node X="151280" Y="13248" />
		<node X="143668" Y="13224" />
		<node X="143698" Y="12185" />
		<node X="144657" Y="10353" />
		<node X="144156" Y="9821" />
		<node X="143148" Y="7939" />
		<node X="143155" Y="4824" />
		<node X="144053" Y="4830" />
	</zone>
	<!-- Innadril Castle HQ Zones -->
	<zone type="HqZone" shape="NPoly" minZ="-2774" maxZ="4000"> <!-- innadrile_castle_headquarter_territory1 -->
		<!-- headquarter_territory -->
		<node X="119963" Y="244504" />
		<node X="112132" Y="244522" />
		<node X="112108" Y="241971" />
		<node X="119943" Y="241963" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-2710" maxZ="4000"> <!-- innadrile_castle_headquarter_territory2 -->
		<!-- headquarter_territory -->
		<node X="119941" Y="253720" />
		<node X="118181" Y="253712" />
		<node X="118177" Y="244794" />
		<node X="119942" Y="244797" />
	</zone>
	<zone type="HqZone" shape="NPoly" minZ="-2678" maxZ="4000"> <!-- innadrile_castle_headquarter_territory3 -->
		<!-- headquarter_territory -->
		<node X="113465" Y="253695" />
		<node X="111828" Y="253690" />
		<node X="111825" Y="244772" />
		<node X="113465" Y="244772" />
	</zone>
	<!-- Goddard Castle HQ Zones -->
	<zone type="HqZone" shape="NPoly" minZ="-2625" maxZ="1875"> <!-- goddard_castle_headquarter_territory -->
		<!-- headquarter_territory -->
		<node X="144715" Y="-43884" />
		<node X="150045" Y="-43884" />
		<node X="150037" Y="-43064" />
		<node X="148924" Y="-42723" />
		<node X="148512" Y="-41841" />
		<node X="148496" Y="-40907" />
		<node X="147063" Y="-40920" />
		<node X="145883" Y="-42805" />
		<node X="144692" Y="-42822" />
	</zone>
	<!-- Rune Castle HQ Zones -->
	<zone type="HqZone" shape="NPoly" minZ="-1780" maxZ="-680"> <!-- rune_castle_headquarter_territory -->
		<!-- headquarter_territory -->
		<node X="26755" Y="-49171" />
		<node X="22310" Y="-49171" />
		<node X="22309" Y="-50415" />
		<node X="21392" Y="-50412" />
		<node X="21391" Y="-49164" />
		<node X="19543" Y="-49168" />
		<node X="19546" Y="-49074" />
		<node X="21387" Y="-49070" />
		<node X="21388" Y="-47783" />
		<node X="22316" Y="-47784" />
		<node X="22316" Y="-49082" />
		<node X="26755" Y="-49082" />
	</zone>
	<!-- Schuttgart Castle HQ Zones -->
	<zone type="HqZone" shape="NPoly" minZ="-3800" maxZ="1700"> <!-- schuttgart_castle_headquarter_territory -->
		<!-- headquarter_territory -->
		<node X="74554" Y="-148009" />
		<node X="80640" Y="-148009" />
		<node X="80631" Y="-147713" />
		<node X="78857" Y="-147120" />
		<node X="78119" Y="-146316" />
		<node X="76767" Y="-146316" />
		<node X="76314" Y="-147099" />
		<node X="74533" Y="-147618" />
	</zone>
	<!-- Clan Hall HQ Zones -->
	<!-- zone name="partisan_agit001_headquarter_territory" type="HqZone" shape="NPoly" minZ="0" maxZ="0" -->
		<!-- stat name="clanHallId" val="21" / -->
	<!-- /zone -->
	<!-- zone name="devastated_castle_headquarter_territory" type="HqZone" shape="NPoly" minZ="-2405" maxZ="595">
		<stat name="clanHallId" val="34" />
		<node X="176740" Y="-13838" />
		<node X="180040" Y="-13838" />
		<node X="180040" Y="-13188" />
		<node X="176740" Y="-13188" />
	</zone -->
	<!-- zone name="bandits'_stronghold_headquarter_territory" type="HqZone" shape="NPoly" minZ="0" maxZ="0" -->
		<!-- stat name="clanHallId" val="35" / -->
	<!-- /zone -->
	<!-- zone name="rainbow_spring_headquarter_territory" type="HqZone" shape="NPoly" minZ="0" maxZ="0" -->
		<!-- stat name="clanHallId" val="62" / -->
	<!-- /zone -->
	<!-- zone name="beast_farm_headquarter_territory" type="HqZone" shape="NPoly" minZ="0" maxZ="0" -->
		<!-- stat name="clanHallId" val="63" / -->
	<!-- /zone -->
	<!-- zone name="fortress_of_dead_headquarter_territory" type="HqZone" shape="NPoly" minZ="-147" maxZ="1853">
		<stat name="clanHallId" val="64" />
		<node X="57502" Y="-31651" />
		<node X="58431" Y="-31607" />
		<node X="59638" Y="-30984" />
		<node X="56685" Y="-30983" />
	</zone -->
</list>
